// Code generated by me. DO NOT EDIT.

package golang

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IntegrationWithExternal::UnsignedLongLongTypeSequence", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IntegrationWithExternalUnsignedLongLongTypeSequence struct {
	__goidl__.IdlObject
	Seq IntegrationWithExternalUnsignedLongLongTypeSeq `json:"Seq"`
}

//noinspection GoSnakeCaseUsage
const IntegrationWithExternalUnsignedLongLongTypeSequenceId_Const = "IDL:IntegrationWithExternal/UnsignedLongLongTypeSequence:1.0"

func (self *IntegrationWithExternalUnsignedLongLongTypeSequence) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IntegrationWithExternalUnsignedLongLongTypeSequence) GoString() string {
	return self.String()
}

func (self *IntegrationWithExternalUnsignedLongLongTypeSequence) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Seq.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IntegrationWithExternalUnsignedLongLongTypeSequence) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IntegrationWithExternalUnsignedLongLongTypeSequence) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.Seq.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IntegrationWithExternalUnsignedLongLongTypeSequence_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IntegrationWithExternalUnsignedLongLongTypeSequenceHelper = IntegrationWithExternalUnsignedLongLongTypeSequence_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IntegrationWithExternalUnsignedLongLongTypeSequenceId_Const,
			__goidl__.StructType,
			"test.idl",
			"xdl_IntegrationWithExternalUnsignedLongLongTypeSequence.go",
			func() __goidl__.IIdlObject {
				return &IntegrationWithExternalUnsignedLongLongTypeSequence{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IntegrationWithExternalUnsignedLongLongTypeSequence{}
			},
			__reflect__.TypeOf((*IntegrationWithExternalUnsignedLongLongTypeSequence)(nil))))
}
