// Code generated by me. DO NOT EDIT.

package golang

import __goidl__ "github.com/bhbosman/goidl"

// Enum declaration: "IntegrationWithExternalNotAligned::EnumValue", generatedBy by: "WriteEnumDcl"
type IntegrationWithExternalNotAlignedEnumValue uint32

//noinspection GoUnusedConst
const (
	IntegrationWithExternalNotAlignedEnumValueValueA IntegrationWithExternalNotAlignedEnumValue = 0
	IntegrationWithExternalNotAlignedEnumValueValueB IntegrationWithExternalNotAlignedEnumValue = 1
)

//noinspection GoSnakeCaseUsage
type IntegrationWithExternalNotAlignedEnumValue_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IntegrationWithExternalNotAlignedEnumValueId_Const = "IDL:IntegrationWithExternalNotAligned/EnumValue:1.0"

func (self IntegrationWithExternalNotAlignedEnumValue_Helper) Id() string {
	return IntegrationWithExternalNotAlignedEnumValueId_Const
}

func (self IntegrationWithExternalNotAlignedEnumValue_Helper) Read(stream __goidl__.IReadAny) (uint32, error) {
	result, err := __goidl__.IdlUInt32Helper.Read(stream)
	return result, err
}

func (self IntegrationWithExternalNotAlignedEnumValue_Helper) Write(stream __goidl__.IWriteAny, v uint32) error {
	return __goidl__.IdlUInt32Helper.Write(stream, v)
}


//noinspection GoUnusedGlobalVariable
var IntegrationWithExternalNotAlignedEnumValueHelper = IntegrationWithExternalNotAlignedEnumValue_Helper{}

func init() {
}
