// Code generated by me. DO NOT EDIT.

package golang

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IntegrationWithExternal::WideStringTypeSequence", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IntegrationWithExternalWideStringTypeSequence struct {
	__goidl__.IdlObject
	Seq IntegrationWithExternalWideStringTypeSeq `json:"Seq"`
}

//noinspection GoSnakeCaseUsage
const IntegrationWithExternalWideStringTypeSequenceId_Const = "IDL:IntegrationWithExternal/WideStringTypeSequence:1.0"

func (self *IntegrationWithExternalWideStringTypeSequence) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IntegrationWithExternalWideStringTypeSequence) GoString() string {
	return self.String()
}

func (self *IntegrationWithExternalWideStringTypeSequence) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Seq.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IntegrationWithExternalWideStringTypeSequence) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IntegrationWithExternalWideStringTypeSequence) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.Seq.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IntegrationWithExternalWideStringTypeSequence_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IntegrationWithExternalWideStringTypeSequenceHelper = IntegrationWithExternalWideStringTypeSequence_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IntegrationWithExternalWideStringTypeSequenceId_Const,
			__goidl__.StructType,
			"test.idl",
			"xdl_IntegrationWithExternalWideStringTypeSequence.go",
			func() __goidl__.IIdlObject {
				return &IntegrationWithExternalWideStringTypeSequence{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IntegrationWithExternalWideStringTypeSequence{}
			},
			__reflect__.TypeOf((*IntegrationWithExternalWideStringTypeSequence)(nil))))
}
