// Code generated by me. DO NOT EDIT.

package golang

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IntegrationWithExternal::StringType", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IntegrationWithExternalStringType struct {
	__goidl__.IdlObject
	Value string `json:"Value"`
}

//noinspection GoSnakeCaseUsage
const IntegrationWithExternalStringTypeId_Const = "IDL:IntegrationWithExternal/StringType:1.0"

func (self *IntegrationWithExternalStringType) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IntegrationWithExternalStringType) GoString() string {
	return self.String()
}

func (self *IntegrationWithExternalStringType) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(StringType)
	self.Value, err = __goidl__.IdlStringHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IntegrationWithExternalStringType) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IntegrationWithExternalStringType) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(StringType)
	err = __goidl__.IdlStringHelper.Write(stream, self.Value)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IntegrationWithExternalStringType_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IntegrationWithExternalStringTypeHelper = IntegrationWithExternalStringType_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IntegrationWithExternalStringTypeId_Const,
			__goidl__.StructType,
			"test.idl",
			"xdl_IntegrationWithExternalStringType.go",
			func() __goidl__.IIdlObject {
				return &IntegrationWithExternalStringType{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IntegrationWithExternalStringType{}
			},
			__reflect__.TypeOf((*IntegrationWithExternalStringType)(nil))))
}
