// Code generated by me. DO NOT EDIT.

package golang

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IntegrationWithExternal::BooleanTypeSequence", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IntegrationWithExternalBooleanTypeSequence struct {
	__goidl__.IdlObject
	Seq IntegrationWithExternalBooleanTypeSeq `json:"Seq"`
}

//noinspection GoSnakeCaseUsage
const IntegrationWithExternalBooleanTypeSequenceId_Const = "IDL:IntegrationWithExternal/BooleanTypeSequence:1.0"

func (self *IntegrationWithExternalBooleanTypeSequence) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IntegrationWithExternalBooleanTypeSequence) GoString() string {
	return self.String()
}

func (self *IntegrationWithExternalBooleanTypeSequence) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Seq.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IntegrationWithExternalBooleanTypeSequence) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IntegrationWithExternalBooleanTypeSequence) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.Seq.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IntegrationWithExternalBooleanTypeSequence_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IntegrationWithExternalBooleanTypeSequenceHelper = IntegrationWithExternalBooleanTypeSequence_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IntegrationWithExternalBooleanTypeSequenceId_Const,
			__goidl__.StructType,
			"test.idl",
			"xdl_IntegrationWithExternalBooleanTypeSequence.go",
			func() __goidl__.IIdlObject {
				return &IntegrationWithExternalBooleanTypeSequence{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IntegrationWithExternalBooleanTypeSequence{}
			},
			__reflect__.TypeOf((*IntegrationWithExternalBooleanTypeSequence)(nil))))
}
