// Code generated by me. DO NOT EDIT.

package golang

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IntegrationWithExternal::CharTypeArray", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IntegrationWithExternalCharTypeArray struct {
	__goidl__.IdlObject
	Value [16]byte `json:"Value"`
}

//noinspection GoSnakeCaseUsage
const IntegrationWithExternalCharTypeArrayId_Const = "IDL:IntegrationWithExternal/CharTypeArray:1.0"

func (self *IntegrationWithExternalCharTypeArray) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IntegrationWithExternalCharTypeArray) GoString() string {
	return self.String()
}

func (self *IntegrationWithExternalCharTypeArray) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(CharType)
	for i0 := 0; i0 < 16; i0++ {
		self.Value[i0], err = __goidl__.IdlOctetHelper.Read(stream)
		if err != nil {
			return err
		}
	}
	return nil
}

func (self *IntegrationWithExternalCharTypeArray) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IntegrationWithExternalCharTypeArray) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(CharType)
	for i0 := 0; i0 < 16; i0++ {
		err = __goidl__.IdlOctetHelper.Write(stream, self.Value[i0])
		if err != nil {
			return err
		}
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IntegrationWithExternalCharTypeArray_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IntegrationWithExternalCharTypeArrayHelper = IntegrationWithExternalCharTypeArray_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IntegrationWithExternalCharTypeArrayId_Const,
			__goidl__.StructType,
			"test.idl",
			"xdl_IntegrationWithExternalCharTypeArray.go",
			func() __goidl__.IIdlObject {
				return &IntegrationWithExternalCharTypeArray{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IntegrationWithExternalCharTypeArray{}
			},
			__reflect__.TypeOf((*IntegrationWithExternalCharTypeArray)(nil))))
}
