// Code generated by me. DO NOT EDIT.

package golang

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IntegrationWithExternal::WideStringTypeArray", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IntegrationWithExternalWideStringTypeArray struct {
	__goidl__.IdlObject
	Value [16]string `json:"Value"`
}

//noinspection GoSnakeCaseUsage
const IntegrationWithExternalWideStringTypeArrayId_Const = "IDL:IntegrationWithExternal/WideStringTypeArray:1.0"

func (self *IntegrationWithExternalWideStringTypeArray) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IntegrationWithExternalWideStringTypeArray) GoString() string {
	return self.String()
}

func (self *IntegrationWithExternalWideStringTypeArray) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(WideStringType)
	for i0 := 0; i0 < 16; i0++ {
		self.Value[i0], err = __goidl__.IdlWideStringHelper.Read(stream)
		if err != nil {
			return err
		}
	}
	return nil
}

func (self *IntegrationWithExternalWideStringTypeArray) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IntegrationWithExternalWideStringTypeArray) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(WideStringType)
	for i0 := 0; i0 < 16; i0++ {
		err = __goidl__.IdlWideStringHelper.Write(stream, self.Value[i0])
		if err != nil {
			return err
		}
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IntegrationWithExternalWideStringTypeArray_Helper struct {
}

//noinspection GoUnusedGlobalVariable
var IntegrationWithExternalWideStringTypeArrayHelper = IntegrationWithExternalWideStringTypeArray_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IntegrationWithExternalWideStringTypeArrayId_Const,
			__goidl__.StructType,
			"test.idl",
			"xdl_IntegrationWithExternalWideStringTypeArray.go",
			func() __goidl__.IIdlObject {
				return &IntegrationWithExternalWideStringTypeArray{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IntegrationWithExternalWideStringTypeArray{}
			},
			__reflect__.TypeOf((*IntegrationWithExternalWideStringTypeArray)(nil))))
}
