// Code generated by me. DO NOT EDIT.

package omg

import __fmt__ "fmt"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Interface declaration: "CORBA::Pollable", generatedBy by: "WriteInterface"
type CorbaPollable interface {
	// Interface operations
	// Original name: "is_ready"
	IsReady(Timeout uint32) (result bool, err error)
	// Original name: "create_pollable_set"
	CreatePollableSet() (result CorbaPollableSet, err error)
}

//noinspection GoSnakeCaseUsage
type CorbaPollable_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaPollableId_Const = "IDL:omg.org/CORBA/Pollable:1.0"

func (self CorbaPollable_Helper) Id() string {
	return CorbaPollableId_Const
}

func (self CorbaPollable_Helper) Read(stream __goidl__.IReadAny) (CorbaPollable, error) {
	return nil, nil
}

func (self CorbaPollable_Helper) Write(stream __goidl__.IWriteAny, v CorbaPollable) error {
	return nil
}

// Interface declaration: "CORBA::DIIPollable", generatedBy by: "WriteInterface"
type CorbaDIIPollable interface {
	//No duplicate operations found in the base interfaces.
	CorbaPollable
	// Interface operations
}

//noinspection GoSnakeCaseUsage
type CorbaDIIPollable_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaDIIPollableId_Const = "IDL:omg.org/CORBA/DIIPollable:1.0"

func (self CorbaDIIPollable_Helper) Id() string {
	return CorbaDIIPollableId_Const
}

func (self CorbaDIIPollable_Helper) Read(stream __goidl__.IReadAny) (CorbaDIIPollable, error) {
	return nil, nil
}

func (self CorbaDIIPollable_Helper) Write(stream __goidl__.IWriteAny, v CorbaDIIPollable) error {
	return nil
}

// Exception declaration: "CORBA::PollableSet::NoPossiblePollable", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type CorbaPollableSetNoPossiblePollable struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaPollableSetNoPossiblePollableId_Const = "IDL:omg.org/CORBA/PollableSet/NoPossiblePollable:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCorbaPollableSetNoPossiblePollable() *CorbaPollableSetNoPossiblePollable {
	//noinspection GoRedundantConversion
	return &CorbaPollableSetNoPossiblePollable{
		IdlObject: __goidl__.IdlObject{
			Id: CorbaPollableSetNoPossiblePollableId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewCorbaPollableSetNoPossiblePollable() *CorbaPollableSetNoPossiblePollable {
	//noinspection GoRedundantConversion
	return &CorbaPollableSetNoPossiblePollable{
		IdlObject: __goidl__.IdlObject{
			Id: CorbaPollableSetNoPossiblePollableId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCorbaPollableSetNoPossiblePollable() *CorbaPollableSetNoPossiblePollable {
	//noinspection GoRedundantConversion
	return &CorbaPollableSetNoPossiblePollable{
		IdlObject: __goidl__.IdlObject{
			Id: CorbaPollableSetNoPossiblePollableId_Const,
		},
	}
}

func (self *CorbaPollableSetNoPossiblePollable) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaPollableSetNoPossiblePollable) Error() string{
	return 	__fmt__.Sprintf("Error of type CorbaPollableSetNoPossiblePollable(%v)", self.String())
}
func (self *CorbaPollableSetNoPossiblePollable) GoString() string {
	return self.String()
}

func (self *CorbaPollableSetNoPossiblePollable) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaPollableSetNoPossiblePollable) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaPollableSetNoPossiblePollable) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaPollableSetNoPossiblePollable_Helper struct {
}

// Exception declaration: "CORBA::PollableSet::UnknownPollable", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type CorbaPollableSetUnknownPollable struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaPollableSetUnknownPollableId_Const = "IDL:omg.org/CORBA/PollableSet/UnknownPollable:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCorbaPollableSetUnknownPollable() *CorbaPollableSetUnknownPollable {
	//noinspection GoRedundantConversion
	return &CorbaPollableSetUnknownPollable{
		IdlObject: __goidl__.IdlObject{
			Id: CorbaPollableSetUnknownPollableId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewCorbaPollableSetUnknownPollable() *CorbaPollableSetUnknownPollable {
	//noinspection GoRedundantConversion
	return &CorbaPollableSetUnknownPollable{
		IdlObject: __goidl__.IdlObject{
			Id: CorbaPollableSetUnknownPollableId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCorbaPollableSetUnknownPollable() *CorbaPollableSetUnknownPollable {
	//noinspection GoRedundantConversion
	return &CorbaPollableSetUnknownPollable{
		IdlObject: __goidl__.IdlObject{
			Id: CorbaPollableSetUnknownPollableId_Const,
		},
	}
}

func (self *CorbaPollableSetUnknownPollable) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaPollableSetUnknownPollable) Error() string{
	return 	__fmt__.Sprintf("Error of type CorbaPollableSetUnknownPollable(%v)", self.String())
}
func (self *CorbaPollableSetUnknownPollable) GoString() string {
	return self.String()
}

func (self *CorbaPollableSetUnknownPollable) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaPollableSetUnknownPollable) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaPollableSetUnknownPollable) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaPollableSetUnknownPollable_Helper struct {
}

// Interface declaration: "CORBA::PollableSet", generatedBy by: "WriteInterface"
type CorbaPollableSet interface {
	// Interface operations
	// Original name: "create_dii_pollable"
	CreateDiiPollable() (result CorbaDIIPollable, err error)
	// Original name: "add_pollable"
	AddPollable(Potential CorbaPollable) (error error)
	//Exceptions for : GetReadyPollable
	//	CorbaPollableSetNoPossiblePollable
	// Original name: "get_ready_pollable"
	GetReadyPollable(Timeout uint32) (result CorbaPollable, err error)
	//Exceptions for : Remove
	//	CorbaPollableSetUnknownPollable
	// Original name: "remove"
	Remove(Potential CorbaPollable) (error error)
	// Original name: "number_left"
	NumberLeft() (result uint16, err error)
}

//noinspection GoSnakeCaseUsage
type CorbaPollableSet_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaPollableSetId_Const = "IDL:omg.org/CORBA/PollableSet:1.0"

func (self CorbaPollableSet_Helper) Id() string {
	return CorbaPollableSetId_Const
}

func (self CorbaPollableSet_Helper) Read(stream __goidl__.IReadAny) (CorbaPollableSet, error) {
	return nil, nil
}

func (self CorbaPollableSet_Helper) Write(stream __goidl__.IWriteAny, v CorbaPollableSet) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaPollableHelper = CorbaPollable_Helper{}

//noinspection GoUnusedGlobalVariable
var CorbaDIIPollableHelper = CorbaDIIPollable_Helper{}

//noinspection GoUnusedGlobalVariable
var CorbaPollableSetNoPossiblePollableHelper = CorbaPollableSetNoPossiblePollable_Helper{}

//noinspection GoUnusedGlobalVariable
var CorbaPollableSetUnknownPollableHelper = CorbaPollableSetUnknownPollable_Helper{}

//noinspection GoUnusedGlobalVariable
var CorbaPollableSetHelper = CorbaPollableSet_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaPollableSetNoPossiblePollableId_Const,
			__yaccidl__.IdlStruct,
			"CORBA_Pollable.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCorbaPollableSetNoPossiblePollable()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewDefaultCorbaPollableSetNoPossiblePollable()
			},
			__reflect__.TypeOf((*CorbaPollableSetNoPossiblePollable)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaPollableSetUnknownPollableId_Const,
			__yaccidl__.IdlStruct,
			"CORBA_Pollable.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCorbaPollableSetUnknownPollable()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewDefaultCorbaPollableSetUnknownPollable()
			},
			__reflect__.TypeOf((*CorbaPollableSetUnknownPollable)(nil))))
}
