// Code generated by me. DO NOT EDIT.

package omg

import __goidl__ "github.com/bhbosman/goidl"

// Native declaration: "CORBA::OpaqueValue", generatedBy by: "WriteNativeDcl"
type CorbaOpaqueValue NativeCorbaOpaqueValue

// Interface declaration: "CORBA::Request", generatedBy by: "WriteInterface"
type CorbaRequest interface {
	// Interface operations
	// Original name: "add_arg"
	AddArg(Name string, ArgType CorbaTypeCode, Value CorbaOpaqueValue, Len int32, ArgFlags uint32) (error error)
	// Original name: "invoke"
	Invoke(InvokeFlags uint32) (error error)
	// Original name: "delete"
	Delete() (error error)
	// Original name: "send"
	Send(InvokeFlags uint32) (error error)
	//Exceptions for : GetResponse
	//	CorbaWrongTransaction
	// Original name: "get_response"
	GetResponse() (error error)
	// Original name: "poll_response"
	PollResponse() (result bool, err error)
	// Original name: "sendp"
	Sendp() (result *__goidl__.IdlObject, err error)
	// Original name: "prepare"
	Prepare(P *__goidl__.IdlObject) (error error)
	// Original name: "sendc"
	Sendc(Handler *__goidl__.IdlObject) (error error)
}

//noinspection GoSnakeCaseUsage
type CorbaRequest_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaRequestId_Const = "IDL:omg.org/CORBA/Request:1.0"

func (self CorbaRequest_Helper) Id() string {
	return CorbaRequestId_Const
}

func (self CorbaRequest_Helper) Read(stream __goidl__.IReadAny) (CorbaRequest, error) {
	return nil, nil
}

func (self CorbaRequest_Helper) Write(stream __goidl__.IWriteAny, v CorbaRequest) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaRequestHelper = CorbaRequest_Helper{}

func init() {
}
