// Code generated by me. DO NOT EDIT.

package omg

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CORBA::Context", generatedBy by: "WriteInterface"
type CorbaContext interface {
	// Interface operations
	// Original name: "set_one_value"
	SetOneValue(PropName string, Value string) (error error)
	// Original name: "set_values"
	SetValues(Values CorbaNVList) (error error)
	// Original name: "get_values"
	GetValues(StartScope string, OpFlags uint32, PropName string) (Values CorbaNVList, error error)
	// Original name: "delete_values"
	DeleteValues(PropName string) (error error)
	// Original name: "create_child"
	CreateChild(CtxName string) (ChildCtx CorbaContext, error error)
	// Original name: "delete"
	Delete(DelFlags uint32) (error error)
}

//noinspection GoSnakeCaseUsage
type CorbaContext_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaContextId_Const = "IDL:omg.org/CORBA/Context:1.0"

func (self CorbaContext_Helper) Id() string {
	return CorbaContextId_Const
}

func (self CorbaContext_Helper) Read(stream __goidl__.IReadAny) (CorbaContext, error) {
	return nil, nil
}

func (self CorbaContext_Helper) Write(stream __goidl__.IWriteAny, v CorbaContext) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaContextHelper = CorbaContext_Helper{}

func init() {
}
