// Code generated by me. DO NOT EDIT.

package omg

import __fmt__ "fmt"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Exception declaration: "CosEventChannelAdmin::AlreadyConnected", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type CosEventChannelAdminAlreadyConnected struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosEventChannelAdminAlreadyConnectedId_Const = "IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCosEventChannelAdminAlreadyConnected() *CosEventChannelAdminAlreadyConnected {
	//noinspection GoRedundantConversion
	return &CosEventChannelAdminAlreadyConnected{
		IdlObject: __goidl__.IdlObject{
			Id: CosEventChannelAdminAlreadyConnectedId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewCosEventChannelAdminAlreadyConnected() *CosEventChannelAdminAlreadyConnected {
	//noinspection GoRedundantConversion
	return &CosEventChannelAdminAlreadyConnected{
		IdlObject: __goidl__.IdlObject{
			Id: CosEventChannelAdminAlreadyConnectedId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCosEventChannelAdminAlreadyConnected() *CosEventChannelAdminAlreadyConnected {
	//noinspection GoRedundantConversion
	return &CosEventChannelAdminAlreadyConnected{
		IdlObject: __goidl__.IdlObject{
			Id: CosEventChannelAdminAlreadyConnectedId_Const,
		},
	}
}

func (self *CosEventChannelAdminAlreadyConnected) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosEventChannelAdminAlreadyConnected) Error() string{
	return 	__fmt__.Sprintf("Error of type CosEventChannelAdminAlreadyConnected(%v)", self.String())
}
func (self *CosEventChannelAdminAlreadyConnected) GoString() string {
	return self.String()
}

func (self *CosEventChannelAdminAlreadyConnected) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventChannelAdminAlreadyConnected) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventChannelAdminAlreadyConnected) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosEventChannelAdminAlreadyConnected_Helper struct {
}

// Exception declaration: "CosEventChannelAdmin::TypeError", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type CosEventChannelAdminTypeError struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosEventChannelAdminTypeErrorId_Const = "IDL:omg.org/CosEventChannelAdmin/TypeError:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCosEventChannelAdminTypeError() *CosEventChannelAdminTypeError {
	//noinspection GoRedundantConversion
	return &CosEventChannelAdminTypeError{
		IdlObject: __goidl__.IdlObject{
			Id: CosEventChannelAdminTypeErrorId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewCosEventChannelAdminTypeError() *CosEventChannelAdminTypeError {
	//noinspection GoRedundantConversion
	return &CosEventChannelAdminTypeError{
		IdlObject: __goidl__.IdlObject{
			Id: CosEventChannelAdminTypeErrorId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCosEventChannelAdminTypeError() *CosEventChannelAdminTypeError {
	//noinspection GoRedundantConversion
	return &CosEventChannelAdminTypeError{
		IdlObject: __goidl__.IdlObject{
			Id: CosEventChannelAdminTypeErrorId_Const,
		},
	}
}

func (self *CosEventChannelAdminTypeError) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosEventChannelAdminTypeError) Error() string{
	return 	__fmt__.Sprintf("Error of type CosEventChannelAdminTypeError(%v)", self.String())
}
func (self *CosEventChannelAdminTypeError) GoString() string {
	return self.String()
}

func (self *CosEventChannelAdminTypeError) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventChannelAdminTypeError) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventChannelAdminTypeError) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosEventChannelAdminTypeError_Helper struct {
}

// Interface declaration: "CosEventChannelAdmin::ProxyPushConsumer", generatedBy by: "WriteInterface"
type CosEventChannelAdminProxyPushConsumer interface {
	//No duplicate operations found in the base interfaces.
	CosEventCommPushConsumer
	// Interface operations
	//Exceptions for : ConnectPushSupplier
	//	CosEventChannelAdminAlreadyConnected
	// Original name: "connect_push_supplier"
	ConnectPushSupplier(PushSupplier CosEventCommPushSupplier) (error error)
}

//noinspection GoSnakeCaseUsage
type CosEventChannelAdminProxyPushConsumer_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosEventChannelAdminProxyPushConsumerId_Const = "IDL:omg.org/CosEventChannelAdmin/ProxyPushConsumer:1.0"

func (self CosEventChannelAdminProxyPushConsumer_Helper) Id() string {
	return CosEventChannelAdminProxyPushConsumerId_Const
}

func (self CosEventChannelAdminProxyPushConsumer_Helper) Read(stream __goidl__.IReadAny) (CosEventChannelAdminProxyPushConsumer, error) {
	return nil, nil
}

func (self CosEventChannelAdminProxyPushConsumer_Helper) Write(stream __goidl__.IWriteAny, v CosEventChannelAdminProxyPushConsumer) error {
	return nil
}

// Interface declaration: "CosEventChannelAdmin::ProxyPullSupplier", generatedBy by: "WriteInterface"
type CosEventChannelAdminProxyPullSupplier interface {
	//No duplicate operations found in the base interfaces.
	CosEventCommPullSupplier
	// Interface operations
	//Exceptions for : ConnectPullConsumer
	//	CosEventChannelAdminAlreadyConnected
	// Original name: "connect_pull_consumer"
	ConnectPullConsumer(PullConsumer CosEventCommPullConsumer) (error error)
}

//noinspection GoSnakeCaseUsage
type CosEventChannelAdminProxyPullSupplier_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosEventChannelAdminProxyPullSupplierId_Const = "IDL:omg.org/CosEventChannelAdmin/ProxyPullSupplier:1.0"

func (self CosEventChannelAdminProxyPullSupplier_Helper) Id() string {
	return CosEventChannelAdminProxyPullSupplierId_Const
}

func (self CosEventChannelAdminProxyPullSupplier_Helper) Read(stream __goidl__.IReadAny) (CosEventChannelAdminProxyPullSupplier, error) {
	return nil, nil
}

func (self CosEventChannelAdminProxyPullSupplier_Helper) Write(stream __goidl__.IWriteAny, v CosEventChannelAdminProxyPullSupplier) error {
	return nil
}

// Interface declaration: "CosEventChannelAdmin::ProxyPullConsumer", generatedBy by: "WriteInterface"
type CosEventChannelAdminProxyPullConsumer interface {
	//No duplicate operations found in the base interfaces.
	CosEventCommPullConsumer
	// Interface operations
	//Exceptions for : ConnectPullSupplier
	//	CosEventChannelAdminAlreadyConnected
	//	CosEventChannelAdminTypeError
	// Original name: "connect_pull_supplier"
	ConnectPullSupplier(PullSupplier CosEventCommPullSupplier) (error error)
}

//noinspection GoSnakeCaseUsage
type CosEventChannelAdminProxyPullConsumer_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosEventChannelAdminProxyPullConsumerId_Const = "IDL:omg.org/CosEventChannelAdmin/ProxyPullConsumer:1.0"

func (self CosEventChannelAdminProxyPullConsumer_Helper) Id() string {
	return CosEventChannelAdminProxyPullConsumerId_Const
}

func (self CosEventChannelAdminProxyPullConsumer_Helper) Read(stream __goidl__.IReadAny) (CosEventChannelAdminProxyPullConsumer, error) {
	return nil, nil
}

func (self CosEventChannelAdminProxyPullConsumer_Helper) Write(stream __goidl__.IWriteAny, v CosEventChannelAdminProxyPullConsumer) error {
	return nil
}

// Interface declaration: "CosEventChannelAdmin::ProxyPushSupplier", generatedBy by: "WriteInterface"
type CosEventChannelAdminProxyPushSupplier interface {
	//No duplicate operations found in the base interfaces.
	CosEventCommPushSupplier
	// Interface operations
	//Exceptions for : ConnectPushConsumer
	//	CosEventChannelAdminAlreadyConnected
	//	CosEventChannelAdminTypeError
	// Original name: "connect_push_consumer"
	ConnectPushConsumer(PushConsumer CosEventCommPushConsumer) (error error)
}

//noinspection GoSnakeCaseUsage
type CosEventChannelAdminProxyPushSupplier_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosEventChannelAdminProxyPushSupplierId_Const = "IDL:omg.org/CosEventChannelAdmin/ProxyPushSupplier:1.0"

func (self CosEventChannelAdminProxyPushSupplier_Helper) Id() string {
	return CosEventChannelAdminProxyPushSupplierId_Const
}

func (self CosEventChannelAdminProxyPushSupplier_Helper) Read(stream __goidl__.IReadAny) (CosEventChannelAdminProxyPushSupplier, error) {
	return nil, nil
}

func (self CosEventChannelAdminProxyPushSupplier_Helper) Write(stream __goidl__.IWriteAny, v CosEventChannelAdminProxyPushSupplier) error {
	return nil
}

// Interface declaration: "CosEventChannelAdmin::ConsumerAdmin", generatedBy by: "WriteInterface"
type CosEventChannelAdminConsumerAdmin interface {
	// Interface operations
	// Original name: "obtain_push_supplier"
	ObtainPushSupplier() (result CosEventChannelAdminProxyPushSupplier, err error)
	// Original name: "obtain_pull_supplier"
	ObtainPullSupplier() (result CosEventChannelAdminProxyPullSupplier, err error)
}

//noinspection GoSnakeCaseUsage
type CosEventChannelAdminConsumerAdmin_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosEventChannelAdminConsumerAdminId_Const = "IDL:omg.org/CosEventChannelAdmin/ConsumerAdmin:1.0"

func (self CosEventChannelAdminConsumerAdmin_Helper) Id() string {
	return CosEventChannelAdminConsumerAdminId_Const
}

func (self CosEventChannelAdminConsumerAdmin_Helper) Read(stream __goidl__.IReadAny) (CosEventChannelAdminConsumerAdmin, error) {
	return nil, nil
}

func (self CosEventChannelAdminConsumerAdmin_Helper) Write(stream __goidl__.IWriteAny, v CosEventChannelAdminConsumerAdmin) error {
	return nil
}

// Interface declaration: "CosEventChannelAdmin::SupplierAdmin", generatedBy by: "WriteInterface"
type CosEventChannelAdminSupplierAdmin interface {
	// Interface operations
	// Original name: "obtain_push_consumer"
	ObtainPushConsumer() (result CosEventChannelAdminProxyPushConsumer, err error)
	// Original name: "obtain_pull_consumer"
	ObtainPullConsumer() (result CosEventChannelAdminProxyPullConsumer, err error)
}

//noinspection GoSnakeCaseUsage
type CosEventChannelAdminSupplierAdmin_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosEventChannelAdminSupplierAdminId_Const = "IDL:omg.org/CosEventChannelAdmin/SupplierAdmin:1.0"

func (self CosEventChannelAdminSupplierAdmin_Helper) Id() string {
	return CosEventChannelAdminSupplierAdminId_Const
}

func (self CosEventChannelAdminSupplierAdmin_Helper) Read(stream __goidl__.IReadAny) (CosEventChannelAdminSupplierAdmin, error) {
	return nil, nil
}

func (self CosEventChannelAdminSupplierAdmin_Helper) Write(stream __goidl__.IWriteAny, v CosEventChannelAdminSupplierAdmin) error {
	return nil
}

// Interface declaration: "CosEventChannelAdmin::EventChannel", generatedBy by: "WriteInterface"
type CosEventChannelAdminEventChannel interface {
	// Interface operations
	// Original name: "for_consumers"
	ForConsumers() (result CosEventChannelAdminConsumerAdmin, err error)
	// Original name: "for_suppliers"
	ForSuppliers() (result CosEventChannelAdminSupplierAdmin, err error)
	// Original name: "destroy"
	Destroy() (error error)
}

//noinspection GoSnakeCaseUsage
type CosEventChannelAdminEventChannel_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosEventChannelAdminEventChannelId_Const = "IDL:omg.org/CosEventChannelAdmin/EventChannel:1.0"

func (self CosEventChannelAdminEventChannel_Helper) Id() string {
	return CosEventChannelAdminEventChannelId_Const
}

func (self CosEventChannelAdminEventChannel_Helper) Read(stream __goidl__.IReadAny) (CosEventChannelAdminEventChannel, error) {
	return nil, nil
}

func (self CosEventChannelAdminEventChannel_Helper) Write(stream __goidl__.IWriteAny, v CosEventChannelAdminEventChannel) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CosEventChannelAdminAlreadyConnectedHelper = CosEventChannelAdminAlreadyConnected_Helper{}

//noinspection GoUnusedGlobalVariable
var CosEventChannelAdminTypeErrorHelper = CosEventChannelAdminTypeError_Helper{}

//noinspection GoUnusedGlobalVariable
var CosEventChannelAdminProxyPushConsumerHelper = CosEventChannelAdminProxyPushConsumer_Helper{}

//noinspection GoUnusedGlobalVariable
var CosEventChannelAdminProxyPullSupplierHelper = CosEventChannelAdminProxyPullSupplier_Helper{}

//noinspection GoUnusedGlobalVariable
var CosEventChannelAdminProxyPullConsumerHelper = CosEventChannelAdminProxyPullConsumer_Helper{}

//noinspection GoUnusedGlobalVariable
var CosEventChannelAdminProxyPushSupplierHelper = CosEventChannelAdminProxyPushSupplier_Helper{}

//noinspection GoUnusedGlobalVariable
var CosEventChannelAdminConsumerAdminHelper = CosEventChannelAdminConsumerAdmin_Helper{}

//noinspection GoUnusedGlobalVariable
var CosEventChannelAdminSupplierAdminHelper = CosEventChannelAdminSupplierAdmin_Helper{}

//noinspection GoUnusedGlobalVariable
var CosEventChannelAdminEventChannelHelper = CosEventChannelAdminEventChannel_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosEventChannelAdminAlreadyConnectedId_Const,
			__yaccidl__.IdlStruct,
			"CosEventChannelAdmin.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCosEventChannelAdminAlreadyConnected()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewDefaultCosEventChannelAdminAlreadyConnected()
			},
			__reflect__.TypeOf((*CosEventChannelAdminAlreadyConnected)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosEventChannelAdminTypeErrorId_Const,
			__yaccidl__.IdlStruct,
			"CosEventChannelAdmin.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCosEventChannelAdminTypeError()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewDefaultCosEventChannelAdminTypeError()
			},
			__reflect__.TypeOf((*CosEventChannelAdminTypeError)(nil))))
}
