// Code generated by me. DO NOT EDIT.

package omg

import __fmt__ "fmt"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// TypeDef declaration: "CosNotification::Istring", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "CosNotification::Istring" from: "string"
type CosNotificationIstring string

//noinspection GoSnakeCaseUsage
type CosNotificationIstring_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationIstringId_Const = "IDL:omg.org/CosNotification/Istring:1.0"

func (self CosNotificationIstring_Helper) Id() string {
	return CosNotificationIstringId_Const
}

func (self CosNotificationIstring_Helper) Read(stream __goidl__.IReadAny) (string, error) {
	result, err := __goidl__.IdlStringHelper.Read(stream)
	return result, err
}

func (self CosNotificationIstring_Helper) Write(stream __goidl__.IWriteAny, v string) error {
	return __goidl__.IdlStringHelper.Write(stream, v)
}

// TypeDef declaration: "CosNotification::PropertyName", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "CosNotification::PropertyName" from: "string"
type CosNotificationPropertyName string

//noinspection GoSnakeCaseUsage
type CosNotificationPropertyName_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationPropertyNameId_Const = "IDL:omg.org/CosNotification/PropertyName:1.0"

func (self CosNotificationPropertyName_Helper) Id() string {
	return CosNotificationPropertyNameId_Const
}

func (self CosNotificationPropertyName_Helper) Read(stream __goidl__.IReadAny) (string, error) {
	result, err := __goidl__.IdlStringHelper.Read(stream)
	return result, err
}

func (self CosNotificationPropertyName_Helper) Write(stream __goidl__.IWriteAny, v string) error {
	return __goidl__.IdlStringHelper.Write(stream, v)
}

// TypeDef declaration: "CosNotification::PropertyValue", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "CosNotification::PropertyValue" from: "__goidl__.IdlAny"
type CosNotificationPropertyValue __goidl__.IdlAny

//noinspection GoSnakeCaseUsage
type CosNotificationPropertyValue_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationPropertyValueId_Const = "IDL:omg.org/CosNotification/PropertyValue:1.0"

func (self CosNotificationPropertyValue_Helper) Id() string {
	return CosNotificationPropertyValueId_Const
}

func (self CosNotificationPropertyValue_Helper) Read(stream __goidl__.IReadAny) (__goidl__.IdlAny, error) {
	result, err := __goidl__.IdlAnyHelper.Read(stream)
	return result, err
}

func (self CosNotificationPropertyValue_Helper) Write(stream __goidl__.IWriteAny, v __goidl__.IdlAny) error {
	return __goidl__.IdlAnyHelper.Write(stream, v)
}

// Struct declaration: "CosNotification::Property", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationProperty struct {
	__goidl__.IdlObject
	Name string `json:"Name"`
	Value __goidl__.IdlAny `json:"Value"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationPropertyId_Const = "IDL:omg.org/CosNotification/Property:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCosNotificationProperty() *CosNotificationProperty {
	//noinspection GoRedundantConversion
	return &CosNotificationProperty{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationPropertyId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "name", Type: "CosNotification::PropertyName" Scope: "IdlTypedef"
		Name: "",
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "value", Type: "CosNotification::PropertyValue" Scope: "IdlTypedef"
		Value: nil,
	}
}

//noinspection GoUnusedExportedFunction
func NewCosNotificationProperty(
	//"StructDclAllParamsConstructorParamService"
	Name string,
	//"StructDclAllParamsConstructorParamService"
	Value __goidl__.IdlAny) *CosNotificationProperty {
	//noinspection GoRedundantConversion
	return &CosNotificationProperty{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationPropertyId_Const,
		},
		Name: Name,
		Value: Value,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCosNotificationProperty(randomGenerator __goidl__.IRandomDataGenerator) *CosNotificationProperty {
	//noinspection GoRedundantConversion
	return &CosNotificationProperty{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationPropertyId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "name", Type: "CosNotification::PropertyName" Scope: "IdlTypedef"
		Name: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotificationProperty)(nil)), "Name"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "value", Type: "CosNotification::PropertyValue" Scope: "IdlTypedef"
		Value: randomGenerator.AnyTypeValue(__reflect__.TypeOf((*CosNotificationProperty)(nil)), "Value"),
	}
}

func (self *CosNotificationProperty) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationProperty) GoString() string {
	return self.String()
}

func (self *CosNotificationProperty) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(StringType)
	self.Name, err = __goidl__.IdlStringHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(AnyType)
	self.Value, err = __goidl__.IdlAnyHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationProperty) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationProperty) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(StringType)
	err = __goidl__.IdlStringHelper.Write(stream, self.Name)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(AnyType)
	err = __goidl__.IdlAnyHelper.Write(stream, self.Value)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationProperty_Helper struct {
}

// TypeDef declaration: "CosNotification::PropertySeq", generatedBy by: "WriteTypeDefOfSequenceDcl"
//Typedef Sequence declaration: CosNotification::PropertySeq
type CosNotificationPropertySeq []*CosNotificationProperty

//noinspection GoSnakeCaseUsage
type CosNotificationPropertySeq_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationPropertySeqId_Const = "IDL:omg.org/CosNotification/PropertySeq:1.0"

func (self CosNotificationPropertySeq_Helper) Id() string {
	return CosNotificationPropertySeqId_Const
}

// WriteTypeDefOfSequenceDcl::WriteExtract
func (self CosNotificationPropertySeq_Helper) Read(stream __goidl__.IReadAny) (CosNotificationPropertySeq, error) {
	n, err := __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		result := make(CosNotificationPropertySeq, n)
		var i uint32
		for i = 0; i < n; i++ {
			result[i] = NewDefaultCosNotificationProperty()
			err = result[i].Read(stream)
			if err != nil {
				return nil, err
			}
		}
		return result, nil
	}
	return nil, nil
}

func (self CosNotificationPropertySeq_Helper) Write(stream __goidl__.IWriteAny, v CosNotificationPropertySeq) error {
	if v == nil {
		return __goidl__.IdlUInt32Helper.Write(stream, 0)
	}
	err := __goidl__.IdlUInt32Helper.Write(stream, uint32(len(v)))
	if err != nil {
		return nil
	}
	for _, item := range v {
			err = item.Write(stream)
		if err != nil {
			return err
		}
	}
	return err
}

// TypeDef declaration: "CosNotification::OptionalHeaderFields", generatedBy by: "WriteTypeDefOfSequenceDcl"
//Typedef Sequence declaration: CosNotification::OptionalHeaderFields
type CosNotificationOptionalHeaderFields []*CosNotificationProperty

//noinspection GoSnakeCaseUsage
type CosNotificationOptionalHeaderFields_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationOptionalHeaderFieldsId_Const = "IDL:omg.org/CosNotification/OptionalHeaderFields:1.0"

func (self CosNotificationOptionalHeaderFields_Helper) Id() string {
	return CosNotificationOptionalHeaderFieldsId_Const
}

// WriteTypeDefOfSequenceDcl::WriteExtract
func (self CosNotificationOptionalHeaderFields_Helper) Read(stream __goidl__.IReadAny) (CosNotificationOptionalHeaderFields, error) {
	n, err := __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		result := make(CosNotificationOptionalHeaderFields, n)
		var i uint32
		for i = 0; i < n; i++ {
			result[i] = NewDefaultCosNotificationProperty()
			err = result[i].Read(stream)
			if err != nil {
				return nil, err
			}
		}
		return result, nil
	}
	return nil, nil
}

func (self CosNotificationOptionalHeaderFields_Helper) Write(stream __goidl__.IWriteAny, v CosNotificationOptionalHeaderFields) error {
	if v == nil {
		return __goidl__.IdlUInt32Helper.Write(stream, 0)
	}
	err := __goidl__.IdlUInt32Helper.Write(stream, uint32(len(v)))
	if err != nil {
		return nil
	}
	for _, item := range v {
			err = item.Write(stream)
		if err != nil {
			return err
		}
	}
	return err
}

// TypeDef declaration: "CosNotification::FilterableEventBody", generatedBy by: "WriteTypeDefOfSequenceDcl"
//Typedef Sequence declaration: CosNotification::FilterableEventBody
type CosNotificationFilterableEventBody []*CosNotificationProperty

//noinspection GoSnakeCaseUsage
type CosNotificationFilterableEventBody_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationFilterableEventBodyId_Const = "IDL:omg.org/CosNotification/FilterableEventBody:1.0"

func (self CosNotificationFilterableEventBody_Helper) Id() string {
	return CosNotificationFilterableEventBodyId_Const
}

// WriteTypeDefOfSequenceDcl::WriteExtract
func (self CosNotificationFilterableEventBody_Helper) Read(stream __goidl__.IReadAny) (CosNotificationFilterableEventBody, error) {
	n, err := __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		result := make(CosNotificationFilterableEventBody, n)
		var i uint32
		for i = 0; i < n; i++ {
			result[i] = NewDefaultCosNotificationProperty()
			err = result[i].Read(stream)
			if err != nil {
				return nil, err
			}
		}
		return result, nil
	}
	return nil, nil
}

func (self CosNotificationFilterableEventBody_Helper) Write(stream __goidl__.IWriteAny, v CosNotificationFilterableEventBody) error {
	if v == nil {
		return __goidl__.IdlUInt32Helper.Write(stream, 0)
	}
	err := __goidl__.IdlUInt32Helper.Write(stream, uint32(len(v)))
	if err != nil {
		return nil
	}
	for _, item := range v {
			err = item.Write(stream)
		if err != nil {
			return err
		}
	}
	return err
}

// TypeDef declaration: "CosNotification::QoSProperties", generatedBy by: "WriteTypeDefOfSequenceDcl"
//Typedef Sequence declaration: CosNotification::QoSProperties
type CosNotificationQoSProperties []*CosNotificationProperty

//noinspection GoSnakeCaseUsage
type CosNotificationQoSProperties_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationQoSPropertiesId_Const = "IDL:omg.org/CosNotification/QoSProperties:1.0"

func (self CosNotificationQoSProperties_Helper) Id() string {
	return CosNotificationQoSPropertiesId_Const
}

// WriteTypeDefOfSequenceDcl::WriteExtract
func (self CosNotificationQoSProperties_Helper) Read(stream __goidl__.IReadAny) (CosNotificationQoSProperties, error) {
	n, err := __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		result := make(CosNotificationQoSProperties, n)
		var i uint32
		for i = 0; i < n; i++ {
			result[i] = NewDefaultCosNotificationProperty()
			err = result[i].Read(stream)
			if err != nil {
				return nil, err
			}
		}
		return result, nil
	}
	return nil, nil
}

func (self CosNotificationQoSProperties_Helper) Write(stream __goidl__.IWriteAny, v CosNotificationQoSProperties) error {
	if v == nil {
		return __goidl__.IdlUInt32Helper.Write(stream, 0)
	}
	err := __goidl__.IdlUInt32Helper.Write(stream, uint32(len(v)))
	if err != nil {
		return nil
	}
	for _, item := range v {
			err = item.Write(stream)
		if err != nil {
			return err
		}
	}
	return err
}

// TypeDef declaration: "CosNotification::AdminProperties", generatedBy by: "WriteTypeDefOfSequenceDcl"
//Typedef Sequence declaration: CosNotification::AdminProperties
type CosNotificationAdminProperties []*CosNotificationProperty

//noinspection GoSnakeCaseUsage
type CosNotificationAdminProperties_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationAdminPropertiesId_Const = "IDL:omg.org/CosNotification/AdminProperties:1.0"

func (self CosNotificationAdminProperties_Helper) Id() string {
	return CosNotificationAdminPropertiesId_Const
}

// WriteTypeDefOfSequenceDcl::WriteExtract
func (self CosNotificationAdminProperties_Helper) Read(stream __goidl__.IReadAny) (CosNotificationAdminProperties, error) {
	n, err := __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		result := make(CosNotificationAdminProperties, n)
		var i uint32
		for i = 0; i < n; i++ {
			result[i] = NewDefaultCosNotificationProperty()
			err = result[i].Read(stream)
			if err != nil {
				return nil, err
			}
		}
		return result, nil
	}
	return nil, nil
}

func (self CosNotificationAdminProperties_Helper) Write(stream __goidl__.IWriteAny, v CosNotificationAdminProperties) error {
	if v == nil {
		return __goidl__.IdlUInt32Helper.Write(stream, 0)
	}
	err := __goidl__.IdlUInt32Helper.Write(stream, uint32(len(v)))
	if err != nil {
		return nil
	}
	for _, item := range v {
			err = item.Write(stream)
		if err != nil {
			return err
		}
	}
	return err
}

// Struct declaration: "CosNotification::EventType", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationEventType struct {
	__goidl__.IdlObject
	DomainName string `json:"DomainName"`
	TypeName string `json:"TypeName"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationEventTypeId_Const = "IDL:omg.org/CosNotification/EventType:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCosNotificationEventType() *CosNotificationEventType {
	//noinspection GoRedundantConversion
	return &CosNotificationEventType{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationEventTypeId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "domain_name", Type: "IdlString" Scope: "StringType"
		DomainName: "",
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "type_name", Type: "IdlString" Scope: "StringType"
		TypeName: "",
	}
}

//noinspection GoUnusedExportedFunction
func NewCosNotificationEventType(
	//"StructDclAllParamsConstructorParamService"
	DomainName string,
	//"StructDclAllParamsConstructorParamService"
	TypeName string) *CosNotificationEventType {
	//noinspection GoRedundantConversion
	return &CosNotificationEventType{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationEventTypeId_Const,
		},
		DomainName: DomainName,
		TypeName: TypeName,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCosNotificationEventType(randomGenerator __goidl__.IRandomDataGenerator) *CosNotificationEventType {
	//noinspection GoRedundantConversion
	return &CosNotificationEventType{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationEventTypeId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "domain_name", Type: "IdlString" Scope: "StringType"
		DomainName: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotificationEventType)(nil)), "DomainName"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "type_name", Type: "IdlString" Scope: "StringType"
		TypeName: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotificationEventType)(nil)), "TypeName"),
	}
}

func (self *CosNotificationEventType) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationEventType) GoString() string {
	return self.String()
}

func (self *CosNotificationEventType) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(StringType)
	self.DomainName, err = __goidl__.IdlStringHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(StringType)
	self.TypeName, err = __goidl__.IdlStringHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationEventType) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationEventType) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(StringType)
	err = __goidl__.IdlStringHelper.Write(stream, self.DomainName)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(StringType)
	err = __goidl__.IdlStringHelper.Write(stream, self.TypeName)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationEventType_Helper struct {
}

// TypeDef declaration: "CosNotification::EventTypeSeq", generatedBy by: "WriteTypeDefOfSequenceDcl"
//Typedef Sequence declaration: CosNotification::EventTypeSeq
type CosNotificationEventTypeSeq []*CosNotificationEventType

//noinspection GoSnakeCaseUsage
type CosNotificationEventTypeSeq_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationEventTypeSeqId_Const = "IDL:omg.org/CosNotification/EventTypeSeq:1.0"

func (self CosNotificationEventTypeSeq_Helper) Id() string {
	return CosNotificationEventTypeSeqId_Const
}

// WriteTypeDefOfSequenceDcl::WriteExtract
func (self CosNotificationEventTypeSeq_Helper) Read(stream __goidl__.IReadAny) (CosNotificationEventTypeSeq, error) {
	n, err := __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		result := make(CosNotificationEventTypeSeq, n)
		var i uint32
		for i = 0; i < n; i++ {
			result[i] = NewDefaultCosNotificationEventType()
			err = result[i].Read(stream)
			if err != nil {
				return nil, err
			}
		}
		return result, nil
	}
	return nil, nil
}

func (self CosNotificationEventTypeSeq_Helper) Write(stream __goidl__.IWriteAny, v CosNotificationEventTypeSeq) error {
	if v == nil {
		return __goidl__.IdlUInt32Helper.Write(stream, 0)
	}
	err := __goidl__.IdlUInt32Helper.Write(stream, uint32(len(v)))
	if err != nil {
		return nil
	}
	for _, item := range v {
			err = item.Write(stream)
		if err != nil {
			return err
		}
	}
	return err
}

// Struct declaration: "CosNotification::PropertyRange", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationPropertyRange struct {
	__goidl__.IdlObject
	LowVal __goidl__.IdlAny `json:"LowVal"`
	HighVal __goidl__.IdlAny `json:"HighVal"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationPropertyRangeId_Const = "IDL:omg.org/CosNotification/PropertyRange:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCosNotificationPropertyRange() *CosNotificationPropertyRange {
	//noinspection GoRedundantConversion
	return &CosNotificationPropertyRange{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationPropertyRangeId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "low_val", Type: "CosNotification::PropertyValue" Scope: "IdlTypedef"
		LowVal: nil,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "high_val", Type: "CosNotification::PropertyValue" Scope: "IdlTypedef"
		HighVal: nil,
	}
}

//noinspection GoUnusedExportedFunction
func NewCosNotificationPropertyRange(
	//"StructDclAllParamsConstructorParamService"
	LowVal __goidl__.IdlAny,
	//"StructDclAllParamsConstructorParamService"
	HighVal __goidl__.IdlAny) *CosNotificationPropertyRange {
	//noinspection GoRedundantConversion
	return &CosNotificationPropertyRange{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationPropertyRangeId_Const,
		},
		LowVal: LowVal,
		HighVal: HighVal,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCosNotificationPropertyRange(randomGenerator __goidl__.IRandomDataGenerator) *CosNotificationPropertyRange {
	//noinspection GoRedundantConversion
	return &CosNotificationPropertyRange{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationPropertyRangeId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "low_val", Type: "CosNotification::PropertyValue" Scope: "IdlTypedef"
		LowVal: randomGenerator.AnyTypeValue(__reflect__.TypeOf((*CosNotificationPropertyRange)(nil)), "LowVal"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "high_val", Type: "CosNotification::PropertyValue" Scope: "IdlTypedef"
		HighVal: randomGenerator.AnyTypeValue(__reflect__.TypeOf((*CosNotificationPropertyRange)(nil)), "HighVal"),
	}
}

func (self *CosNotificationPropertyRange) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationPropertyRange) GoString() string {
	return self.String()
}

func (self *CosNotificationPropertyRange) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(AnyType)
	self.LowVal, err = __goidl__.IdlAnyHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(AnyType)
	self.HighVal, err = __goidl__.IdlAnyHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationPropertyRange) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationPropertyRange) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(AnyType)
	err = __goidl__.IdlAnyHelper.Write(stream, self.LowVal)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(AnyType)
	err = __goidl__.IdlAnyHelper.Write(stream, self.HighVal)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationPropertyRange_Helper struct {
}

// Struct declaration: "CosNotification::NamedPropertyRange", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationNamedPropertyRange struct {
	__goidl__.IdlObject
	Name string `json:"Name"`
	Range CosNotificationPropertyRange `json:"Range"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationNamedPropertyRangeId_Const = "IDL:omg.org/CosNotification/NamedPropertyRange:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCosNotificationNamedPropertyRange() *CosNotificationNamedPropertyRange {
	//noinspection GoRedundantConversion
	return &CosNotificationNamedPropertyRange{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationNamedPropertyRangeId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "name", Type: "CosNotification::PropertyName" Scope: "IdlTypedef"
		Name: "",
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "range", Type: "CosNotification::PropertyRange" Scope: "IdlStruct"
		Range: CosNotificationPropertyRange{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "low_val", Type: "CosNotification::PropertyValue" Scope: "IdlTypedef"
		LowVal: nil,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "high_val", Type: "CosNotification::PropertyValue" Scope: "IdlTypedef"
		HighVal: nil,
	},
	}
}

//noinspection GoUnusedExportedFunction
func NewCosNotificationNamedPropertyRange(
	//"StructDclAllParamsConstructorParamService"
	Name string,
	//"StructDclAllParamsConstructorParamService"
	Range CosNotificationPropertyRange) *CosNotificationNamedPropertyRange {
	//noinspection GoRedundantConversion
	return &CosNotificationNamedPropertyRange{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationNamedPropertyRangeId_Const,
		},
		Name: Name,
		Range: Range,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCosNotificationNamedPropertyRange(randomGenerator __goidl__.IRandomDataGenerator) *CosNotificationNamedPropertyRange {
	//noinspection GoRedundantConversion
	return &CosNotificationNamedPropertyRange{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationNamedPropertyRangeId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "name", Type: "CosNotification::PropertyName" Scope: "IdlTypedef"
		Name: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotificationNamedPropertyRange)(nil)), "Name"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "range", Type: "CosNotification::PropertyRange" Scope: "IdlStruct"
		Range: CosNotificationPropertyRange{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "low_val", Type: "CosNotification::PropertyValue" Scope: "IdlTypedef"
		LowVal: randomGenerator.AnyTypeValue(__reflect__.TypeOf((*CosNotificationNamedPropertyRange)(nil)), "LowVal"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "high_val", Type: "CosNotification::PropertyValue" Scope: "IdlTypedef"
		HighVal: randomGenerator.AnyTypeValue(__reflect__.TypeOf((*CosNotificationNamedPropertyRange)(nil)), "HighVal"),
	},
	}
}

func (self *CosNotificationNamedPropertyRange) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationNamedPropertyRange) GoString() string {
	return self.String()
}

func (self *CosNotificationNamedPropertyRange) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(StringType)
	self.Name, err = __goidl__.IdlStringHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Range.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationNamedPropertyRange) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationNamedPropertyRange) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(StringType)
	err = __goidl__.IdlStringHelper.Write(stream, self.Name)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.Range.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationNamedPropertyRange_Helper struct {
}

// TypeDef declaration: "CosNotification::NamedPropertyRangeSeq", generatedBy by: "WriteTypeDefOfSequenceDcl"
//Typedef Sequence declaration: CosNotification::NamedPropertyRangeSeq
type CosNotificationNamedPropertyRangeSeq []*CosNotificationNamedPropertyRange

//noinspection GoSnakeCaseUsage
type CosNotificationNamedPropertyRangeSeq_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationNamedPropertyRangeSeqId_Const = "IDL:omg.org/CosNotification/NamedPropertyRangeSeq:1.0"

func (self CosNotificationNamedPropertyRangeSeq_Helper) Id() string {
	return CosNotificationNamedPropertyRangeSeqId_Const
}

// WriteTypeDefOfSequenceDcl::WriteExtract
func (self CosNotificationNamedPropertyRangeSeq_Helper) Read(stream __goidl__.IReadAny) (CosNotificationNamedPropertyRangeSeq, error) {
	n, err := __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		result := make(CosNotificationNamedPropertyRangeSeq, n)
		var i uint32
		for i = 0; i < n; i++ {
			result[i] = NewDefaultCosNotificationNamedPropertyRange()
			err = result[i].Read(stream)
			if err != nil {
				return nil, err
			}
		}
		return result, nil
	}
	return nil, nil
}

func (self CosNotificationNamedPropertyRangeSeq_Helper) Write(stream __goidl__.IWriteAny, v CosNotificationNamedPropertyRangeSeq) error {
	if v == nil {
		return __goidl__.IdlUInt32Helper.Write(stream, 0)
	}
	err := __goidl__.IdlUInt32Helper.Write(stream, uint32(len(v)))
	if err != nil {
		return nil
	}
	for _, item := range v {
			err = item.Write(stream)
		if err != nil {
			return err
		}
	}
	return err
}

// Enum declaration: "CosNotification::QoSError_code", generatedBy by: "WriteEnumDcl"
type CosNotificationQoSErrorCode uint32

//noinspection GoUnusedConst
const (
	CosNotificationQoSErrorCodeUnsupportedProperty CosNotificationQoSErrorCode = 0
	CosNotificationQoSErrorCodeUnavailableProperty CosNotificationQoSErrorCode = 1
	CosNotificationQoSErrorCodeUnsupportedValue    CosNotificationQoSErrorCode = 2
	CosNotificationQoSErrorCodeUnavailableValue    CosNotificationQoSErrorCode = 3
	CosNotificationQoSErrorCodeBadProperty         CosNotificationQoSErrorCode = 4
	CosNotificationQoSErrorCodeBadType             CosNotificationQoSErrorCode = 5
	CosNotificationQoSErrorCodeBadValue            CosNotificationQoSErrorCode = 6
)

//noinspection GoSnakeCaseUsage
type CosNotificationQoSErrorCode_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationQoSErrorCodeId_Const = "IDL:omg.org/CosNotification/QoSError_code:1.0"

func (self CosNotificationQoSErrorCode_Helper) Id() string {
	return CosNotificationQoSErrorCodeId_Const
}

func (self CosNotificationQoSErrorCode_Helper) Read(stream __goidl__.IReadAny) (uint32, error) {
	result, err := __goidl__.IdlUInt32Helper.Read(stream)
	return result, err
}

func (self CosNotificationQoSErrorCode_Helper) Write(stream __goidl__.IWriteAny, v uint32) error {
	return __goidl__.IdlUInt32Helper.Write(stream, v)
}

// Struct declaration: "CosNotification::PropertyError", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationPropertyError struct {
	__goidl__.IdlObject
	Code uint32 `json:"Code"`
	Name string `json:"Name"`
	AvailableRange CosNotificationPropertyRange `json:"AvailableRange"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationPropertyErrorId_Const = "IDL:omg.org/CosNotification/PropertyError:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCosNotificationPropertyError() *CosNotificationPropertyError {
	//noinspection GoRedundantConversion
	return &CosNotificationPropertyError{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationPropertyErrorId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "code", Type: "CosNotification::QoSError_code" Scope: "IdlEnum"
		Code: 0,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "name", Type: "CosNotification::PropertyName" Scope: "IdlTypedef"
		Name: "",
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "available_range", Type: "CosNotification::PropertyRange" Scope: "IdlStruct"
		AvailableRange: CosNotificationPropertyRange{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "low_val", Type: "CosNotification::PropertyValue" Scope: "IdlTypedef"
		LowVal: nil,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "high_val", Type: "CosNotification::PropertyValue" Scope: "IdlTypedef"
		HighVal: nil,
	},
	}
}

//noinspection GoUnusedExportedFunction
func NewCosNotificationPropertyError(
	//"StructDclAllParamsConstructorParamService"
	Code uint32,
	//"StructDclAllParamsConstructorParamService"
	Name string,
	//"StructDclAllParamsConstructorParamService"
	AvailableRange CosNotificationPropertyRange) *CosNotificationPropertyError {
	//noinspection GoRedundantConversion
	return &CosNotificationPropertyError{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationPropertyErrorId_Const,
		},
		Code: Code,
		Name: Name,
		AvailableRange: AvailableRange,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCosNotificationPropertyError(randomGenerator __goidl__.IRandomDataGenerator) *CosNotificationPropertyError {
	//noinspection GoRedundantConversion
	return &CosNotificationPropertyError{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationPropertyErrorId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "code", Type: "CosNotification::QoSError_code" Scope: "IdlEnum"
		Code: randomGenerator.EnumTypeValue(__reflect__.TypeOf((*CosNotificationPropertyError)(nil)), "Code"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "name", Type: "CosNotification::PropertyName" Scope: "IdlTypedef"
		Name: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotificationPropertyError)(nil)), "Name"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "available_range", Type: "CosNotification::PropertyRange" Scope: "IdlStruct"
		AvailableRange: CosNotificationPropertyRange{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "low_val", Type: "CosNotification::PropertyValue" Scope: "IdlTypedef"
		LowVal: randomGenerator.AnyTypeValue(__reflect__.TypeOf((*CosNotificationPropertyError)(nil)), "LowVal"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "high_val", Type: "CosNotification::PropertyValue" Scope: "IdlTypedef"
		HighVal: randomGenerator.AnyTypeValue(__reflect__.TypeOf((*CosNotificationPropertyError)(nil)), "HighVal"),
	},
	}
}

func (self *CosNotificationPropertyError) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationPropertyError) GoString() string {
	return self.String()
}

func (self *CosNotificationPropertyError) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlEnum)
	self.Code, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(StringType)
	self.Name, err = __goidl__.IdlStringHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.AvailableRange.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationPropertyError) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationPropertyError) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlEnum)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.Code)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(StringType)
	err = __goidl__.IdlStringHelper.Write(stream, self.Name)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.AvailableRange.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationPropertyError_Helper struct {
}

// TypeDef declaration: "CosNotification::PropertyErrorSeq", generatedBy by: "WriteTypeDefOfSequenceDcl"
//Typedef Sequence declaration: CosNotification::PropertyErrorSeq
type CosNotificationPropertyErrorSeq []*CosNotificationPropertyError

//noinspection GoSnakeCaseUsage
type CosNotificationPropertyErrorSeq_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationPropertyErrorSeqId_Const = "IDL:omg.org/CosNotification/PropertyErrorSeq:1.0"

func (self CosNotificationPropertyErrorSeq_Helper) Id() string {
	return CosNotificationPropertyErrorSeqId_Const
}

// WriteTypeDefOfSequenceDcl::WriteExtract
func (self CosNotificationPropertyErrorSeq_Helper) Read(stream __goidl__.IReadAny) (CosNotificationPropertyErrorSeq, error) {
	n, err := __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		result := make(CosNotificationPropertyErrorSeq, n)
		var i uint32
		for i = 0; i < n; i++ {
			result[i] = NewDefaultCosNotificationPropertyError()
			err = result[i].Read(stream)
			if err != nil {
				return nil, err
			}
		}
		return result, nil
	}
	return nil, nil
}

func (self CosNotificationPropertyErrorSeq_Helper) Write(stream __goidl__.IWriteAny, v CosNotificationPropertyErrorSeq) error {
	if v == nil {
		return __goidl__.IdlUInt32Helper.Write(stream, 0)
	}
	err := __goidl__.IdlUInt32Helper.Write(stream, uint32(len(v)))
	if err != nil {
		return nil
	}
	for _, item := range v {
			err = item.Write(stream)
		if err != nil {
			return err
		}
	}
	return err
}

// Exception declaration: "CosNotification::UnsupportedQoS", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type CosNotificationUnsupportedQoS struct {
	__goidl__.IdlObject
	QosErr CosNotificationPropertyErrorSeq `json:"QosErr"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationUnsupportedQoSId_Const = "IDL:omg.org/CosNotification/UnsupportedQoS:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCosNotificationUnsupportedQoS() *CosNotificationUnsupportedQoS {
	//noinspection GoRedundantConversion
	return &CosNotificationUnsupportedQoS{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationUnsupportedQoSId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "qos_err", Type: "CosNotification::PropertyErrorSeq" Scope: "IdlTypedef"
		QosErr: CosNotificationPropertyErrorSeq(nil),
	}
}

//noinspection GoUnusedExportedFunction
func NewCosNotificationUnsupportedQoS(
	//"StructDclAllParamsConstructorParamService"
	QosErr CosNotificationPropertyErrorSeq) *CosNotificationUnsupportedQoS {
	//noinspection GoRedundantConversion
	return &CosNotificationUnsupportedQoS{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationUnsupportedQoSId_Const,
		},
		QosErr: QosErr,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCosNotificationUnsupportedQoS(randomGenerator __goidl__.IRandomDataGenerator) *CosNotificationUnsupportedQoS {
	//noinspection GoRedundantConversion
	return &CosNotificationUnsupportedQoS{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationUnsupportedQoSId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "qos_err", Type: "CosNotification::PropertyErrorSeq" Scope: "IdlTypedef"
		QosErr: CosNotificationPropertyErrorSeq(nil),
	}
}

func (self *CosNotificationUnsupportedQoS) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationUnsupportedQoS) Error() string{
	return 	__fmt__.Sprintf("Error of type CosNotificationUnsupportedQoS(%v)", self.String())
}
func (self *CosNotificationUnsupportedQoS) GoString() string {
	return self.String()
}

func (self *CosNotificationUnsupportedQoS) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlSequence)
	self.QosErr, err = CosNotificationPropertyErrorSeqHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationUnsupportedQoS) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationUnsupportedQoS) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlSequence)
	err = CosNotificationPropertyErrorSeqHelper.Write(stream, self.QosErr)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationUnsupportedQoS_Helper struct {
}

// Exception declaration: "CosNotification::UnsupportedAdmin", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type CosNotificationUnsupportedAdmin struct {
	__goidl__.IdlObject
	AdminErr CosNotificationPropertyErrorSeq `json:"AdminErr"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationUnsupportedAdminId_Const = "IDL:omg.org/CosNotification/UnsupportedAdmin:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCosNotificationUnsupportedAdmin() *CosNotificationUnsupportedAdmin {
	//noinspection GoRedundantConversion
	return &CosNotificationUnsupportedAdmin{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationUnsupportedAdminId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "admin_err", Type: "CosNotification::PropertyErrorSeq" Scope: "IdlTypedef"
		AdminErr: CosNotificationPropertyErrorSeq(nil),
	}
}

//noinspection GoUnusedExportedFunction
func NewCosNotificationUnsupportedAdmin(
	//"StructDclAllParamsConstructorParamService"
	AdminErr CosNotificationPropertyErrorSeq) *CosNotificationUnsupportedAdmin {
	//noinspection GoRedundantConversion
	return &CosNotificationUnsupportedAdmin{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationUnsupportedAdminId_Const,
		},
		AdminErr: AdminErr,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCosNotificationUnsupportedAdmin(randomGenerator __goidl__.IRandomDataGenerator) *CosNotificationUnsupportedAdmin {
	//noinspection GoRedundantConversion
	return &CosNotificationUnsupportedAdmin{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationUnsupportedAdminId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "admin_err", Type: "CosNotification::PropertyErrorSeq" Scope: "IdlTypedef"
		AdminErr: CosNotificationPropertyErrorSeq(nil),
	}
}

func (self *CosNotificationUnsupportedAdmin) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationUnsupportedAdmin) Error() string{
	return 	__fmt__.Sprintf("Error of type CosNotificationUnsupportedAdmin(%v)", self.String())
}
func (self *CosNotificationUnsupportedAdmin) GoString() string {
	return self.String()
}

func (self *CosNotificationUnsupportedAdmin) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlSequence)
	self.AdminErr, err = CosNotificationPropertyErrorSeqHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationUnsupportedAdmin) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationUnsupportedAdmin) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlSequence)
	err = CosNotificationPropertyErrorSeqHelper.Write(stream, self.AdminErr)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationUnsupportedAdmin_Helper struct {
}

// Struct declaration: "CosNotification::FixedEventHeader", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationFixedEventHeader struct {
	__goidl__.IdlObject
	EventType CosNotificationEventType `json:"EventType"`
	EventName string `json:"EventName"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationFixedEventHeaderId_Const = "IDL:omg.org/CosNotification/FixedEventHeader:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCosNotificationFixedEventHeader() *CosNotificationFixedEventHeader {
	//noinspection GoRedundantConversion
	return &CosNotificationFixedEventHeader{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationFixedEventHeaderId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "event_type", Type: "CosNotification::EventType" Scope: "IdlStruct"
		EventType: CosNotificationEventType{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "domain_name", Type: "IdlString" Scope: "StringType"
		DomainName: "",
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "type_name", Type: "IdlString" Scope: "StringType"
		TypeName: "",
	},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "event_name", Type: "IdlString" Scope: "StringType"
		EventName: "",
	}
}

//noinspection GoUnusedExportedFunction
func NewCosNotificationFixedEventHeader(
	//"StructDclAllParamsConstructorParamService"
	EventType CosNotificationEventType,
	//"StructDclAllParamsConstructorParamService"
	EventName string) *CosNotificationFixedEventHeader {
	//noinspection GoRedundantConversion
	return &CosNotificationFixedEventHeader{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationFixedEventHeaderId_Const,
		},
		EventType: EventType,
		EventName: EventName,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCosNotificationFixedEventHeader(randomGenerator __goidl__.IRandomDataGenerator) *CosNotificationFixedEventHeader {
	//noinspection GoRedundantConversion
	return &CosNotificationFixedEventHeader{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationFixedEventHeaderId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "event_type", Type: "CosNotification::EventType" Scope: "IdlStruct"
		EventType: CosNotificationEventType{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "domain_name", Type: "IdlString" Scope: "StringType"
		DomainName: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotificationFixedEventHeader)(nil)), "DomainName"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "type_name", Type: "IdlString" Scope: "StringType"
		TypeName: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotificationFixedEventHeader)(nil)), "TypeName"),
	},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "event_name", Type: "IdlString" Scope: "StringType"
		EventName: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotificationFixedEventHeader)(nil)), "EventName"),
	}
}

func (self *CosNotificationFixedEventHeader) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationFixedEventHeader) GoString() string {
	return self.String()
}

func (self *CosNotificationFixedEventHeader) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.EventType.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(StringType)
	self.EventName, err = __goidl__.IdlStringHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationFixedEventHeader) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationFixedEventHeader) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.EventType.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(StringType)
	err = __goidl__.IdlStringHelper.Write(stream, self.EventName)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationFixedEventHeader_Helper struct {
}

// Struct declaration: "CosNotification::EventHeader", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationEventHeader struct {
	__goidl__.IdlObject
	FixedHeader CosNotificationFixedEventHeader `json:"FixedHeader"`
	VariableHeader CosNotificationOptionalHeaderFields `json:"VariableHeader"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationEventHeaderId_Const = "IDL:omg.org/CosNotification/EventHeader:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCosNotificationEventHeader() *CosNotificationEventHeader {
	//noinspection GoRedundantConversion
	return &CosNotificationEventHeader{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationEventHeaderId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "fixed_header", Type: "CosNotification::FixedEventHeader" Scope: "IdlStruct"
		FixedHeader: CosNotificationFixedEventHeader{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "event_type", Type: "CosNotification::EventType" Scope: "IdlStruct"
		EventType: CosNotificationEventType{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "domain_name", Type: "IdlString" Scope: "StringType"
		DomainName: "",
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "type_name", Type: "IdlString" Scope: "StringType"
		TypeName: "",
	},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "event_name", Type: "IdlString" Scope: "StringType"
		EventName: "",
	},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "variable_header", Type: "CosNotification::OptionalHeaderFields" Scope: "IdlTypedef"
		VariableHeader: CosNotificationOptionalHeaderFields(CosNotificationOptionalHeaderFields(nil)),
	}
}

//noinspection GoUnusedExportedFunction
func NewCosNotificationEventHeader(
	//"StructDclAllParamsConstructorParamService"
	FixedHeader CosNotificationFixedEventHeader,
	//"StructDclAllParamsConstructorParamService"
	VariableHeader CosNotificationOptionalHeaderFields) *CosNotificationEventHeader {
	//noinspection GoRedundantConversion
	return &CosNotificationEventHeader{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationEventHeaderId_Const,
		},
		FixedHeader: FixedHeader,
		VariableHeader: VariableHeader,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCosNotificationEventHeader(randomGenerator __goidl__.IRandomDataGenerator) *CosNotificationEventHeader {
	//noinspection GoRedundantConversion
	return &CosNotificationEventHeader{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationEventHeaderId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "fixed_header", Type: "CosNotification::FixedEventHeader" Scope: "IdlStruct"
		FixedHeader: CosNotificationFixedEventHeader{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "event_type", Type: "CosNotification::EventType" Scope: "IdlStruct"
		EventType: CosNotificationEventType{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "domain_name", Type: "IdlString" Scope: "StringType"
		DomainName: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotificationEventHeader)(nil)), "DomainName"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "type_name", Type: "IdlString" Scope: "StringType"
		TypeName: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotificationEventHeader)(nil)), "TypeName"),
	},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "event_name", Type: "IdlString" Scope: "StringType"
		EventName: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotificationEventHeader)(nil)), "EventName"),
	},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "variable_header", Type: "CosNotification::OptionalHeaderFields" Scope: "IdlTypedef"
		VariableHeader: CosNotificationOptionalHeaderFields(CosNotificationOptionalHeaderFields(nil)),
	}
}

func (self *CosNotificationEventHeader) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationEventHeader) GoString() string {
	return self.String()
}

func (self *CosNotificationEventHeader) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.FixedHeader.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlSequence)
	self.VariableHeader, err = CosNotificationOptionalHeaderFieldsHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationEventHeader) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationEventHeader) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.FixedHeader.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlSequence)
	err = CosNotificationOptionalHeaderFieldsHelper.Write(stream, self.VariableHeader)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationEventHeader_Helper struct {
}

// Struct declaration: "CosNotification::StructuredEvent", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationStructuredEvent struct {
	__goidl__.IdlObject
	Header CosNotificationEventHeader `json:"Header"`
	FilterableData CosNotificationFilterableEventBody `json:"FilterableData"`
	RemainderOfBody __goidl__.IdlAny `json:"RemainderOfBody"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationStructuredEventId_Const = "IDL:omg.org/CosNotification/StructuredEvent:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCosNotificationStructuredEvent() *CosNotificationStructuredEvent {
	//noinspection GoRedundantConversion
	return &CosNotificationStructuredEvent{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationStructuredEventId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "header", Type: "CosNotification::EventHeader" Scope: "IdlStruct"
		Header: CosNotificationEventHeader{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "fixed_header", Type: "CosNotification::FixedEventHeader" Scope: "IdlStruct"
		FixedHeader: CosNotificationFixedEventHeader{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "event_type", Type: "CosNotification::EventType" Scope: "IdlStruct"
		EventType: CosNotificationEventType{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "domain_name", Type: "IdlString" Scope: "StringType"
		DomainName: "",
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "type_name", Type: "IdlString" Scope: "StringType"
		TypeName: "",
	},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "event_name", Type: "IdlString" Scope: "StringType"
		EventName: "",
	},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "variable_header", Type: "CosNotification::OptionalHeaderFields" Scope: "IdlTypedef"
		VariableHeader: CosNotificationOptionalHeaderFields(CosNotificationOptionalHeaderFields(nil)),
	},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "filterable_data", Type: "CosNotification::FilterableEventBody" Scope: "IdlTypedef"
		FilterableData: CosNotificationFilterableEventBody(CosNotificationFilterableEventBody(nil)),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "remainder_of_body", Type: "IdlAny" Scope: "AnyType"
		RemainderOfBody: nil,
	}
}

//noinspection GoUnusedExportedFunction
func NewCosNotificationStructuredEvent(
	//"StructDclAllParamsConstructorParamService"
	Header CosNotificationEventHeader,
	//"StructDclAllParamsConstructorParamService"
	FilterableData CosNotificationFilterableEventBody,
	//"StructDclAllParamsConstructorParamService"
	RemainderOfBody __goidl__.IdlAny) *CosNotificationStructuredEvent {
	//noinspection GoRedundantConversion
	return &CosNotificationStructuredEvent{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationStructuredEventId_Const,
		},
		Header: Header,
		FilterableData: FilterableData,
		RemainderOfBody: RemainderOfBody,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCosNotificationStructuredEvent(randomGenerator __goidl__.IRandomDataGenerator) *CosNotificationStructuredEvent {
	//noinspection GoRedundantConversion
	return &CosNotificationStructuredEvent{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotificationStructuredEventId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "header", Type: "CosNotification::EventHeader" Scope: "IdlStruct"
		Header: CosNotificationEventHeader{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "fixed_header", Type: "CosNotification::FixedEventHeader" Scope: "IdlStruct"
		FixedHeader: CosNotificationFixedEventHeader{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "event_type", Type: "CosNotification::EventType" Scope: "IdlStruct"
		EventType: CosNotificationEventType{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "domain_name", Type: "IdlString" Scope: "StringType"
		DomainName: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotificationStructuredEvent)(nil)), "DomainName"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "type_name", Type: "IdlString" Scope: "StringType"
		TypeName: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotificationStructuredEvent)(nil)), "TypeName"),
	},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "event_name", Type: "IdlString" Scope: "StringType"
		EventName: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotificationStructuredEvent)(nil)), "EventName"),
	},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "variable_header", Type: "CosNotification::OptionalHeaderFields" Scope: "IdlTypedef"
		VariableHeader: CosNotificationOptionalHeaderFields(CosNotificationOptionalHeaderFields(nil)),
	},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "filterable_data", Type: "CosNotification::FilterableEventBody" Scope: "IdlTypedef"
		FilterableData: CosNotificationFilterableEventBody(CosNotificationFilterableEventBody(nil)),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "remainder_of_body", Type: "IdlAny" Scope: "AnyType"
		RemainderOfBody: randomGenerator.AnyTypeValue(__reflect__.TypeOf((*CosNotificationStructuredEvent)(nil)), "RemainderOfBody"),
	}
}

func (self *CosNotificationStructuredEvent) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationStructuredEvent) GoString() string {
	return self.String()
}

func (self *CosNotificationStructuredEvent) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Header.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlSequence)
	self.FilterableData, err = CosNotificationFilterableEventBodyHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(AnyType)
	self.RemainderOfBody, err = __goidl__.IdlAnyHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationStructuredEvent) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationStructuredEvent) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.Header.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlSequence)
	err = CosNotificationFilterableEventBodyHelper.Write(stream, self.FilterableData)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(AnyType)
	err = __goidl__.IdlAnyHelper.Write(stream, self.RemainderOfBody)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationStructuredEvent_Helper struct {
}

// TypeDef declaration: "CosNotification::EventBatch", generatedBy by: "WriteTypeDefOfSequenceDcl"
//Typedef Sequence declaration: CosNotification::EventBatch
type CosNotificationEventBatch []*CosNotificationStructuredEvent

//noinspection GoSnakeCaseUsage
type CosNotificationEventBatch_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationEventBatchId_Const = "IDL:omg.org/CosNotification/EventBatch:1.0"

func (self CosNotificationEventBatch_Helper) Id() string {
	return CosNotificationEventBatchId_Const
}

// WriteTypeDefOfSequenceDcl::WriteExtract
func (self CosNotificationEventBatch_Helper) Read(stream __goidl__.IReadAny) (CosNotificationEventBatch, error) {
	n, err := __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		result := make(CosNotificationEventBatch, n)
		var i uint32
		for i = 0; i < n; i++ {
			result[i] = NewDefaultCosNotificationStructuredEvent()
			err = result[i].Read(stream)
			if err != nil {
				return nil, err
			}
		}
		return result, nil
	}
	return nil, nil
}

func (self CosNotificationEventBatch_Helper) Write(stream __goidl__.IWriteAny, v CosNotificationEventBatch) error {
	if v == nil {
		return __goidl__.IdlUInt32Helper.Write(stream, 0)
	}
	err := __goidl__.IdlUInt32Helper.Write(stream, uint32(len(v)))
	if err != nil {
		return nil
	}
	for _, item := range v {
			err = item.Write(stream)
		if err != nil {
			return err
		}
	}
	return err
}

// Constant declaration: "CosNotification::EventReliability", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationEventReliability string = "EventReliability"

// Constant declaration: "CosNotification::BestEffort", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationBestEffort int16 = 0

// Constant declaration: "CosNotification::Persistent", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationPersistent int16 = 1

// Constant declaration: "CosNotification::ConnectionReliability", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationConnectionReliability string = "ConnectionReliability"

// Constant declaration: "CosNotification::Priority", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationPriority string = "Priority"

// Constant declaration: "CosNotification::LowestPriority", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationLowestPriority int16 = -32767

// Constant declaration: "CosNotification::HighestPriority", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationHighestPriority int16 = 32767

// Constant declaration: "CosNotification::DefaultPriority", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationDefaultPriority int16 = 0

// Constant declaration: "CosNotification::StartTime", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationStartTime string = "StartTime"

// Constant declaration: "CosNotification::StopTime", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationStopTime string = "StopTime"

// Constant declaration: "CosNotification::Timeout", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationTimeout string = "Timeout"

// Constant declaration: "CosNotification::OrderPolicy", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationOrderPolicy string = "OrderPolicy"

// Constant declaration: "CosNotification::AnyOrder", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationAnyOrder int16 = 0

// Constant declaration: "CosNotification::FifoOrder", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationFifoOrder int16 = 1

// Constant declaration: "CosNotification::PriorityOrder", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationPriorityOrder int16 = 2

// Constant declaration: "CosNotification::DeadlineOrder", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationDeadlineOrder int16 = 3

// Constant declaration: "CosNotification::DiscardPolicy", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationDiscardPolicy string = "DiscardPolicy"

// Constant declaration: "CosNotification::LifoOrder", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationLifoOrder int16 = 4

// Constant declaration: "CosNotification::MaximumBatchSize", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationMaximumBatchSize string = "MaximumBatchSize"

// Constant declaration: "CosNotification::PacingInterval", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationPacingInterval string = "PacingInterval"

// Constant declaration: "CosNotification::StartTimeSupported", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationStartTimeSupported string = "StartTimeSupported"

// Constant declaration: "CosNotification::StopTimeSupported", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationStopTimeSupported string = "StopTimeSupported"

// Constant declaration: "CosNotification::MaxEventsPerConsumer", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationMaxEventsPerConsumer string = "MaxEventsPerConsumer"

// Interface declaration: "CosNotification::QoSAdmin", generatedBy by: "WriteInterface"
type CosNotificationQoSAdmin interface {
	// Interface operations
	// Original name: "get_qos"
	GetQos() (result CosNotificationQoSProperties, err error)
	//Exceptions for : SetQos
	//	CosNotificationUnsupportedQoS
	// Original name: "set_qos"
	SetQos(Qos CosNotificationQoSProperties) (error error)
	//Exceptions for : ValidateQos
	//	CosNotificationUnsupportedQoS
	// Original name: "validate_qos"
	ValidateQos(RequiredQos CosNotificationQoSProperties) (AvailableQos CosNotificationNamedPropertyRangeSeq, error error)
}

//noinspection GoSnakeCaseUsage
type CosNotificationQoSAdmin_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationQoSAdminId_Const = "IDL:omg.org/CosNotification/QoSAdmin:1.0"

func (self CosNotificationQoSAdmin_Helper) Id() string {
	return CosNotificationQoSAdminId_Const
}

func (self CosNotificationQoSAdmin_Helper) Read(stream __goidl__.IReadAny) (CosNotificationQoSAdmin, error) {
	return nil, nil
}

func (self CosNotificationQoSAdmin_Helper) Write(stream __goidl__.IWriteAny, v CosNotificationQoSAdmin) error {
	return nil
}

// Constant declaration: "CosNotification::MaxQueueLength", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationMaxQueueLength string = "MaxQueueLength"

// Constant declaration: "CosNotification::MaxConsumers", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationMaxConsumers string = "MaxConsumers"

// Constant declaration: "CosNotification::MaxSuppliers", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationMaxSuppliers string = "MaxSuppliers"

// Constant declaration: "CosNotification::RejectNewEvents", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationRejectNewEvents string = "RejectNewEvents"

// Interface declaration: "CosNotification::AdminPropertiesAdmin", generatedBy by: "WriteInterface"
type CosNotificationAdminPropertiesAdmin interface {
	// Interface operations
	// Original name: "get_admin"
	GetAdmin() (result CosNotificationAdminProperties, err error)
	//Exceptions for : SetAdmin
	//	CosNotificationUnsupportedAdmin
	// Original name: "set_admin"
	SetAdmin(Admin CosNotificationAdminProperties) (error error)
}

//noinspection GoSnakeCaseUsage
type CosNotificationAdminPropertiesAdmin_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationAdminPropertiesAdminId_Const = "IDL:omg.org/CosNotification/AdminPropertiesAdmin:1.0"

func (self CosNotificationAdminPropertiesAdmin_Helper) Id() string {
	return CosNotificationAdminPropertiesAdminId_Const
}

func (self CosNotificationAdminPropertiesAdmin_Helper) Read(stream __goidl__.IReadAny) (CosNotificationAdminPropertiesAdmin, error) {
	return nil, nil
}

func (self CosNotificationAdminPropertiesAdmin_Helper) Write(stream __goidl__.IWriteAny, v CosNotificationAdminPropertiesAdmin) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CosNotificationIstringHelper = CosNotificationIstring_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationPropertyNameHelper = CosNotificationPropertyName_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationPropertyValueHelper = CosNotificationPropertyValue_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationPropertyHelper = CosNotificationProperty_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationPropertySeqHelper = CosNotificationPropertySeq_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationOptionalHeaderFieldsHelper = CosNotificationOptionalHeaderFields_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationFilterableEventBodyHelper = CosNotificationFilterableEventBody_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationQoSPropertiesHelper = CosNotificationQoSProperties_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationAdminPropertiesHelper = CosNotificationAdminProperties_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationEventTypeHelper = CosNotificationEventType_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationEventTypeSeqHelper = CosNotificationEventTypeSeq_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationPropertyRangeHelper = CosNotificationPropertyRange_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationNamedPropertyRangeHelper = CosNotificationNamedPropertyRange_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationNamedPropertyRangeSeqHelper = CosNotificationNamedPropertyRangeSeq_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationQoSErrorCodeHelper = CosNotificationQoSErrorCode_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationPropertyErrorHelper = CosNotificationPropertyError_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationPropertyErrorSeqHelper = CosNotificationPropertyErrorSeq_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationUnsupportedQoSHelper = CosNotificationUnsupportedQoS_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationUnsupportedAdminHelper = CosNotificationUnsupportedAdmin_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationFixedEventHeaderHelper = CosNotificationFixedEventHeader_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationEventHeaderHelper = CosNotificationEventHeader_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationStructuredEventHelper = CosNotificationStructuredEvent_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationEventBatchHelper = CosNotificationEventBatch_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationQoSAdminHelper = CosNotificationQoSAdmin_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationAdminPropertiesAdminHelper = CosNotificationAdminPropertiesAdmin_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationPropertyId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCosNotificationProperty()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomCosNotificationProperty(generator)
			},
			__reflect__.TypeOf((*CosNotificationProperty)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationEventTypeId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCosNotificationEventType()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomCosNotificationEventType(generator)
			},
			__reflect__.TypeOf((*CosNotificationEventType)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationPropertyRangeId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCosNotificationPropertyRange()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomCosNotificationPropertyRange(generator)
			},
			__reflect__.TypeOf((*CosNotificationPropertyRange)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationNamedPropertyRangeId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCosNotificationNamedPropertyRange()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomCosNotificationNamedPropertyRange(generator)
			},
			__reflect__.TypeOf((*CosNotificationNamedPropertyRange)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationPropertyErrorId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCosNotificationPropertyError()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomCosNotificationPropertyError(generator)
			},
			__reflect__.TypeOf((*CosNotificationPropertyError)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationUnsupportedQoSId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCosNotificationUnsupportedQoS()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomCosNotificationUnsupportedQoS(generator)
			},
			__reflect__.TypeOf((*CosNotificationUnsupportedQoS)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationUnsupportedAdminId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCosNotificationUnsupportedAdmin()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomCosNotificationUnsupportedAdmin(generator)
			},
			__reflect__.TypeOf((*CosNotificationUnsupportedAdmin)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationFixedEventHeaderId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCosNotificationFixedEventHeader()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomCosNotificationFixedEventHeader(generator)
			},
			__reflect__.TypeOf((*CosNotificationFixedEventHeader)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationEventHeaderId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCosNotificationEventHeader()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomCosNotificationEventHeader(generator)
			},
			__reflect__.TypeOf((*CosNotificationEventHeader)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationStructuredEventId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCosNotificationStructuredEvent()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomCosNotificationStructuredEvent(generator)
			},
			__reflect__.TypeOf((*CosNotificationStructuredEvent)(nil))))
}
