// Code generated by me. DO NOT EDIT.

package omg

import __fmt__ "fmt"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Exception declaration: "CosNotifyComm::InvalidEventType", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type CosNotifyCommInvalidEventType struct {
	__goidl__.IdlObject
	Type CosNotificationEventType `json:"Type"`
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommInvalidEventTypeId_Const = "IDL:omg.org/CosNotifyComm/InvalidEventType:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCosNotifyCommInvalidEventType() *CosNotifyCommInvalidEventType {
	//noinspection GoRedundantConversion
	return &CosNotifyCommInvalidEventType{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotifyCommInvalidEventTypeId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "type", Type: "CosNotification::EventType" Scope: "IdlStruct"
		Type: CosNotificationEventType{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "domain_name", Type: "IdlString" Scope: "StringType"
		DomainName: "",
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "type_name", Type: "IdlString" Scope: "StringType"
		TypeName: "",
	},
	}
}

//noinspection GoUnusedExportedFunction
func NewCosNotifyCommInvalidEventType(
	//"StructDclAllParamsConstructorParamService"
	Type CosNotificationEventType) *CosNotifyCommInvalidEventType {
	//noinspection GoRedundantConversion
	return &CosNotifyCommInvalidEventType{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotifyCommInvalidEventTypeId_Const,
		},
		Type: Type,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCosNotifyCommInvalidEventType(randomGenerator __goidl__.IRandomDataGenerator) *CosNotifyCommInvalidEventType {
	//noinspection GoRedundantConversion
	return &CosNotifyCommInvalidEventType{
		IdlObject: __goidl__.IdlObject{
			Id: CosNotifyCommInvalidEventTypeId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "type", Type: "CosNotification::EventType" Scope: "IdlStruct"
		Type: CosNotificationEventType{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "domain_name", Type: "IdlString" Scope: "StringType"
		DomainName: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotifyCommInvalidEventType)(nil)), "DomainName"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "type_name", Type: "IdlString" Scope: "StringType"
		TypeName: randomGenerator.StringTypeValue(__reflect__.TypeOf((*CosNotifyCommInvalidEventType)(nil)), "TypeName"),
	},
	}
}

func (self *CosNotifyCommInvalidEventType) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotifyCommInvalidEventType) Error() string{
	return 	__fmt__.Sprintf("Error of type CosNotifyCommInvalidEventType(%v)", self.String())
}
func (self *CosNotifyCommInvalidEventType) GoString() string {
	return self.String()
}

func (self *CosNotifyCommInvalidEventType) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Type.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotifyCommInvalidEventType) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotifyCommInvalidEventType) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.Type.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommInvalidEventType_Helper struct {
}

// Interface declaration: "CosNotifyComm::NotifyPublish", generatedBy by: "WriteInterface"
type CosNotifyCommNotifyPublish interface {
	// Interface operations
	//Exceptions for : OfferChange
	//	CosNotifyCommInvalidEventType
	// Original name: "offer_change"
	OfferChange(Added CosNotificationEventTypeSeq, Removed CosNotificationEventTypeSeq) (error error)
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommNotifyPublish_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommNotifyPublishId_Const = "IDL:omg.org/CosNotifyComm/NotifyPublish:1.0"

func (self CosNotifyCommNotifyPublish_Helper) Id() string {
	return CosNotifyCommNotifyPublishId_Const
}

func (self CosNotifyCommNotifyPublish_Helper) Read(stream __goidl__.IReadAny) (CosNotifyCommNotifyPublish, error) {
	return nil, nil
}

func (self CosNotifyCommNotifyPublish_Helper) Write(stream __goidl__.IWriteAny, v CosNotifyCommNotifyPublish) error {
	return nil
}

// Interface declaration: "CosNotifyComm::NotifySubscribe", generatedBy by: "WriteInterface"
type CosNotifyCommNotifySubscribe interface {
	// Interface operations
	//Exceptions for : SubscriptionChange
	//	CosNotifyCommInvalidEventType
	// Original name: "subscription_change"
	SubscriptionChange(Added CosNotificationEventTypeSeq, Removed CosNotificationEventTypeSeq) (error error)
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommNotifySubscribe_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommNotifySubscribeId_Const = "IDL:omg.org/CosNotifyComm/NotifySubscribe:1.0"

func (self CosNotifyCommNotifySubscribe_Helper) Id() string {
	return CosNotifyCommNotifySubscribeId_Const
}

func (self CosNotifyCommNotifySubscribe_Helper) Read(stream __goidl__.IReadAny) (CosNotifyCommNotifySubscribe, error) {
	return nil, nil
}

func (self CosNotifyCommNotifySubscribe_Helper) Write(stream __goidl__.IWriteAny, v CosNotifyCommNotifySubscribe) error {
	return nil
}

// Interface declaration: "CosNotifyComm::PushConsumer", generatedBy by: "WriteInterface"
type CosNotifyCommPushConsumer interface {
	//No duplicate operations found in the base interfaces.
	CosNotifyCommNotifyPublish
	CosEventCommPushConsumer
	// Interface operations
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommPushConsumer_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommPushConsumerId_Const = "IDL:omg.org/CosNotifyComm/PushConsumer:1.0"

func (self CosNotifyCommPushConsumer_Helper) Id() string {
	return CosNotifyCommPushConsumerId_Const
}

func (self CosNotifyCommPushConsumer_Helper) Read(stream __goidl__.IReadAny) (CosNotifyCommPushConsumer, error) {
	return nil, nil
}

func (self CosNotifyCommPushConsumer_Helper) Write(stream __goidl__.IWriteAny, v CosNotifyCommPushConsumer) error {
	return nil
}

// Interface declaration: "CosNotifyComm::PullConsumer", generatedBy by: "WriteInterface"
type CosNotifyCommPullConsumer interface {
	//No duplicate operations found in the base interfaces.
	CosNotifyCommNotifyPublish
	CosEventCommPullConsumer
	// Interface operations
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommPullConsumer_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommPullConsumerId_Const = "IDL:omg.org/CosNotifyComm/PullConsumer:1.0"

func (self CosNotifyCommPullConsumer_Helper) Id() string {
	return CosNotifyCommPullConsumerId_Const
}

func (self CosNotifyCommPullConsumer_Helper) Read(stream __goidl__.IReadAny) (CosNotifyCommPullConsumer, error) {
	return nil, nil
}

func (self CosNotifyCommPullConsumer_Helper) Write(stream __goidl__.IWriteAny, v CosNotifyCommPullConsumer) error {
	return nil
}

// Interface declaration: "CosNotifyComm::PullSupplier", generatedBy by: "WriteInterface"
type CosNotifyCommPullSupplier interface {
	//No duplicate operations found in the base interfaces.
	CosNotifyCommNotifySubscribe
	CosEventCommPullSupplier
	// Interface operations
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommPullSupplier_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommPullSupplierId_Const = "IDL:omg.org/CosNotifyComm/PullSupplier:1.0"

func (self CosNotifyCommPullSupplier_Helper) Id() string {
	return CosNotifyCommPullSupplierId_Const
}

func (self CosNotifyCommPullSupplier_Helper) Read(stream __goidl__.IReadAny) (CosNotifyCommPullSupplier, error) {
	return nil, nil
}

func (self CosNotifyCommPullSupplier_Helper) Write(stream __goidl__.IWriteAny, v CosNotifyCommPullSupplier) error {
	return nil
}

// Interface declaration: "CosNotifyComm::PushSupplier", generatedBy by: "WriteInterface"
type CosNotifyCommPushSupplier interface {
	//No duplicate operations found in the base interfaces.
	CosNotifyCommNotifySubscribe
	CosEventCommPushSupplier
	// Interface operations
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommPushSupplier_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommPushSupplierId_Const = "IDL:omg.org/CosNotifyComm/PushSupplier:1.0"

func (self CosNotifyCommPushSupplier_Helper) Id() string {
	return CosNotifyCommPushSupplierId_Const
}

func (self CosNotifyCommPushSupplier_Helper) Read(stream __goidl__.IReadAny) (CosNotifyCommPushSupplier, error) {
	return nil, nil
}

func (self CosNotifyCommPushSupplier_Helper) Write(stream __goidl__.IWriteAny, v CosNotifyCommPushSupplier) error {
	return nil
}

// Interface declaration: "CosNotifyComm::StructuredPushConsumer", generatedBy by: "WriteInterface"
type CosNotifyCommStructuredPushConsumer interface {
	//No duplicate operations found in the base interfaces.
	CosNotifyCommNotifyPublish
	// Interface operations
	//Exceptions for : PushStructuredEvent
	//	CosEventCommDisconnected
	// Original name: "push_structured_event"
	PushStructuredEvent(Notification *CosNotificationStructuredEvent) (error error)
	// Original name: "disconnect_structured_push_consumer"
	DisconnectStructuredPushConsumer() (error error)
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommStructuredPushConsumer_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommStructuredPushConsumerId_Const = "IDL:omg.org/CosNotifyComm/StructuredPushConsumer:1.0"

func (self CosNotifyCommStructuredPushConsumer_Helper) Id() string {
	return CosNotifyCommStructuredPushConsumerId_Const
}

func (self CosNotifyCommStructuredPushConsumer_Helper) Read(stream __goidl__.IReadAny) (CosNotifyCommStructuredPushConsumer, error) {
	return nil, nil
}

func (self CosNotifyCommStructuredPushConsumer_Helper) Write(stream __goidl__.IWriteAny, v CosNotifyCommStructuredPushConsumer) error {
	return nil
}

// Interface declaration: "CosNotifyComm::StructuredPullConsumer", generatedBy by: "WriteInterface"
type CosNotifyCommStructuredPullConsumer interface {
	//No duplicate operations found in the base interfaces.
	CosNotifyCommNotifyPublish
	// Interface operations
	// Original name: "disconnect_structured_pull_consumer"
	DisconnectStructuredPullConsumer() (error error)
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommStructuredPullConsumer_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommStructuredPullConsumerId_Const = "IDL:omg.org/CosNotifyComm/StructuredPullConsumer:1.0"

func (self CosNotifyCommStructuredPullConsumer_Helper) Id() string {
	return CosNotifyCommStructuredPullConsumerId_Const
}

func (self CosNotifyCommStructuredPullConsumer_Helper) Read(stream __goidl__.IReadAny) (CosNotifyCommStructuredPullConsumer, error) {
	return nil, nil
}

func (self CosNotifyCommStructuredPullConsumer_Helper) Write(stream __goidl__.IWriteAny, v CosNotifyCommStructuredPullConsumer) error {
	return nil
}

// Interface declaration: "CosNotifyComm::StructuredPullSupplier", generatedBy by: "WriteInterface"
type CosNotifyCommStructuredPullSupplier interface {
	//No duplicate operations found in the base interfaces.
	CosNotifyCommNotifySubscribe
	// Interface operations
	//Exceptions for : PullStructuredEvent
	//	CosEventCommDisconnected
	// Original name: "pull_structured_event"
	PullStructuredEvent() (result *CosNotificationStructuredEvent, err error)
	//Exceptions for : TryPullStructuredEvent
	//	CosEventCommDisconnected
	// Original name: "try_pull_structured_event"
	TryPullStructuredEvent() (HasEvent bool, result *CosNotificationStructuredEvent, err error)
	// Original name: "disconnect_structured_pull_supplier"
	DisconnectStructuredPullSupplier() (error error)
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommStructuredPullSupplier_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommStructuredPullSupplierId_Const = "IDL:omg.org/CosNotifyComm/StructuredPullSupplier:1.0"

func (self CosNotifyCommStructuredPullSupplier_Helper) Id() string {
	return CosNotifyCommStructuredPullSupplierId_Const
}

func (self CosNotifyCommStructuredPullSupplier_Helper) Read(stream __goidl__.IReadAny) (CosNotifyCommStructuredPullSupplier, error) {
	return nil, nil
}

func (self CosNotifyCommStructuredPullSupplier_Helper) Write(stream __goidl__.IWriteAny, v CosNotifyCommStructuredPullSupplier) error {
	return nil
}

// Interface declaration: "CosNotifyComm::StructuredPushSupplier", generatedBy by: "WriteInterface"
type CosNotifyCommStructuredPushSupplier interface {
	//No duplicate operations found in the base interfaces.
	CosNotifyCommNotifySubscribe
	// Interface operations
	// Original name: "disconnect_structured_push_supplier"
	DisconnectStructuredPushSupplier() (error error)
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommStructuredPushSupplier_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommStructuredPushSupplierId_Const = "IDL:omg.org/CosNotifyComm/StructuredPushSupplier:1.0"

func (self CosNotifyCommStructuredPushSupplier_Helper) Id() string {
	return CosNotifyCommStructuredPushSupplierId_Const
}

func (self CosNotifyCommStructuredPushSupplier_Helper) Read(stream __goidl__.IReadAny) (CosNotifyCommStructuredPushSupplier, error) {
	return nil, nil
}

func (self CosNotifyCommStructuredPushSupplier_Helper) Write(stream __goidl__.IWriteAny, v CosNotifyCommStructuredPushSupplier) error {
	return nil
}

// Interface declaration: "CosNotifyComm::SequencePushConsumer", generatedBy by: "WriteInterface"
type CosNotifyCommSequencePushConsumer interface {
	//No duplicate operations found in the base interfaces.
	CosNotifyCommNotifyPublish
	// Interface operations
	//Exceptions for : PushStructuredEvents
	//	CosEventCommDisconnected
	// Original name: "push_structured_events"
	PushStructuredEvents(Notifications CosNotificationEventBatch) (error error)
	// Original name: "disconnect_sequence_push_consumer"
	DisconnectSequencePushConsumer() (error error)
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommSequencePushConsumer_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommSequencePushConsumerId_Const = "IDL:omg.org/CosNotifyComm/SequencePushConsumer:1.0"

func (self CosNotifyCommSequencePushConsumer_Helper) Id() string {
	return CosNotifyCommSequencePushConsumerId_Const
}

func (self CosNotifyCommSequencePushConsumer_Helper) Read(stream __goidl__.IReadAny) (CosNotifyCommSequencePushConsumer, error) {
	return nil, nil
}

func (self CosNotifyCommSequencePushConsumer_Helper) Write(stream __goidl__.IWriteAny, v CosNotifyCommSequencePushConsumer) error {
	return nil
}

// Interface declaration: "CosNotifyComm::SequencePullConsumer", generatedBy by: "WriteInterface"
type CosNotifyCommSequencePullConsumer interface {
	//No duplicate operations found in the base interfaces.
	CosNotifyCommNotifyPublish
	// Interface operations
	// Original name: "disconnect_sequence_pull_consumer"
	DisconnectSequencePullConsumer() (error error)
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommSequencePullConsumer_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommSequencePullConsumerId_Const = "IDL:omg.org/CosNotifyComm/SequencePullConsumer:1.0"

func (self CosNotifyCommSequencePullConsumer_Helper) Id() string {
	return CosNotifyCommSequencePullConsumerId_Const
}

func (self CosNotifyCommSequencePullConsumer_Helper) Read(stream __goidl__.IReadAny) (CosNotifyCommSequencePullConsumer, error) {
	return nil, nil
}

func (self CosNotifyCommSequencePullConsumer_Helper) Write(stream __goidl__.IWriteAny, v CosNotifyCommSequencePullConsumer) error {
	return nil
}

// Interface declaration: "CosNotifyComm::SequencePullSupplier", generatedBy by: "WriteInterface"
type CosNotifyCommSequencePullSupplier interface {
	//No duplicate operations found in the base interfaces.
	CosNotifyCommNotifySubscribe
	// Interface operations
	//Exceptions for : PullStructuredEvents
	//	CosEventCommDisconnected
	// Original name: "pull_structured_events"
	PullStructuredEvents(MaxNumber int32) (result CosNotificationEventBatch, err error)
	//Exceptions for : TryPullStructuredEvents
	//	CosEventCommDisconnected
	// Original name: "try_pull_structured_events"
	TryPullStructuredEvents(MaxNumber int32) (HasEvent bool, result CosNotificationEventBatch, err error)
	// Original name: "disconnect_sequence_pull_supplier"
	DisconnectSequencePullSupplier() (error error)
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommSequencePullSupplier_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommSequencePullSupplierId_Const = "IDL:omg.org/CosNotifyComm/SequencePullSupplier:1.0"

func (self CosNotifyCommSequencePullSupplier_Helper) Id() string {
	return CosNotifyCommSequencePullSupplierId_Const
}

func (self CosNotifyCommSequencePullSupplier_Helper) Read(stream __goidl__.IReadAny) (CosNotifyCommSequencePullSupplier, error) {
	return nil, nil
}

func (self CosNotifyCommSequencePullSupplier_Helper) Write(stream __goidl__.IWriteAny, v CosNotifyCommSequencePullSupplier) error {
	return nil
}

// Interface declaration: "CosNotifyComm::SequencePushSupplier", generatedBy by: "WriteInterface"
type CosNotifyCommSequencePushSupplier interface {
	//No duplicate operations found in the base interfaces.
	CosNotifyCommNotifySubscribe
	// Interface operations
	// Original name: "disconnect_sequence_push_supplier"
	DisconnectSequencePushSupplier() (error error)
}

//noinspection GoSnakeCaseUsage
type CosNotifyCommSequencePushSupplier_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotifyCommSequencePushSupplierId_Const = "IDL:omg.org/CosNotifyComm/SequencePushSupplier:1.0"

func (self CosNotifyCommSequencePushSupplier_Helper) Id() string {
	return CosNotifyCommSequencePushSupplierId_Const
}

func (self CosNotifyCommSequencePushSupplier_Helper) Read(stream __goidl__.IReadAny) (CosNotifyCommSequencePushSupplier, error) {
	return nil, nil
}

func (self CosNotifyCommSequencePushSupplier_Helper) Write(stream __goidl__.IWriteAny, v CosNotifyCommSequencePushSupplier) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CosNotifyCommInvalidEventTypeHelper = CosNotifyCommInvalidEventType_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotifyCommNotifyPublishHelper = CosNotifyCommNotifyPublish_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotifyCommNotifySubscribeHelper = CosNotifyCommNotifySubscribe_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotifyCommPushConsumerHelper = CosNotifyCommPushConsumer_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotifyCommPullConsumerHelper = CosNotifyCommPullConsumer_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotifyCommPullSupplierHelper = CosNotifyCommPullSupplier_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotifyCommPushSupplierHelper = CosNotifyCommPushSupplier_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotifyCommStructuredPushConsumerHelper = CosNotifyCommStructuredPushConsumer_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotifyCommStructuredPullConsumerHelper = CosNotifyCommStructuredPullConsumer_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotifyCommStructuredPullSupplierHelper = CosNotifyCommStructuredPullSupplier_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotifyCommStructuredPushSupplierHelper = CosNotifyCommStructuredPushSupplier_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotifyCommSequencePushConsumerHelper = CosNotifyCommSequencePushConsumer_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotifyCommSequencePullConsumerHelper = CosNotifyCommSequencePullConsumer_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotifyCommSequencePullSupplierHelper = CosNotifyCommSequencePullSupplier_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotifyCommSequencePushSupplierHelper = CosNotifyCommSequencePushSupplier_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotifyCommInvalidEventTypeId_Const,
			__yaccidl__.IdlStruct,
			"CosNotifyComm.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultCosNotifyCommInvalidEventType()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomCosNotifyCommInvalidEventType(generator)
			},
			__reflect__.TypeOf((*CosNotifyCommInvalidEventType)(nil))))
}
