// Code generated by me. DO NOT EDIT.

package omg

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CosTypedNotifyComm::TypedPushConsumer", generatedBy by: "WriteInterface"
type CosTypedNotifyCommTypedPushConsumer interface {
	//No duplicate operations found in the base interfaces.
	CosTypedEventCommTypedPushConsumer
	CosNotifyCommNotifyPublish
	// Interface operations
}

//noinspection GoSnakeCaseUsage
type CosTypedNotifyCommTypedPushConsumer_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosTypedNotifyCommTypedPushConsumerId_Const = "IDL:omg.org/CosTypedNotifyComm/TypedPushConsumer:1.0"

func (self CosTypedNotifyCommTypedPushConsumer_Helper) Id() string {
	return CosTypedNotifyCommTypedPushConsumerId_Const
}

func (self CosTypedNotifyCommTypedPushConsumer_Helper) Read(stream __goidl__.IReadAny) (CosTypedNotifyCommTypedPushConsumer, error) {
	return nil, nil
}

func (self CosTypedNotifyCommTypedPushConsumer_Helper) Write(stream __goidl__.IWriteAny, v CosTypedNotifyCommTypedPushConsumer) error {
	return nil
}

// Interface declaration: "CosTypedNotifyComm::TypedPullSupplier", generatedBy by: "WriteInterface"
type CosTypedNotifyCommTypedPullSupplier interface {
	//No duplicate operations found in the base interfaces.
	CosTypedEventCommTypedPullSupplier
	CosNotifyCommNotifySubscribe
	// Interface operations
}

//noinspection GoSnakeCaseUsage
type CosTypedNotifyCommTypedPullSupplier_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosTypedNotifyCommTypedPullSupplierId_Const = "IDL:omg.org/CosTypedNotifyComm/TypedPullSupplier:1.0"

func (self CosTypedNotifyCommTypedPullSupplier_Helper) Id() string {
	return CosTypedNotifyCommTypedPullSupplierId_Const
}

func (self CosTypedNotifyCommTypedPullSupplier_Helper) Read(stream __goidl__.IReadAny) (CosTypedNotifyCommTypedPullSupplier, error) {
	return nil, nil
}

func (self CosTypedNotifyCommTypedPullSupplier_Helper) Write(stream __goidl__.IWriteAny, v CosTypedNotifyCommTypedPullSupplier) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CosTypedNotifyCommTypedPushConsumerHelper = CosTypedNotifyCommTypedPushConsumer_Helper{}

//noinspection GoUnusedGlobalVariable
var CosTypedNotifyCommTypedPullSupplierHelper = CosTypedNotifyCommTypedPullSupplier_Helper{}

func init() {
}
