package IntegrationWithExternal;


/**
* IntegrationWithExternal/_IIntegrationWithExternalStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public class _IIntegrationWithExternalStub extends org.omg.CORBA.portable.ObjectImpl implements IntegrationWithExternal.IIntegrationWithExternal
{

  public IntegrationWithExternal.OctetType MethodOctetType (IntegrationWithExternal.OctetType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodOctetType", true);
                IntegrationWithExternal.OctetTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.OctetType $result = IntegrationWithExternal.OctetTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodOctetType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodOctetType

  public IntegrationWithExternal.OctetTypeArray MethodOctetTypeArray (IntegrationWithExternal.OctetTypeArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodOctetTypeArray", true);
                IntegrationWithExternal.OctetTypeArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.OctetTypeArray $result = IntegrationWithExternal.OctetTypeArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodOctetTypeArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodOctetTypeArray

  public IntegrationWithExternal.OctetTypeSequence MethodOctetTypeSequence (IntegrationWithExternal.OctetTypeSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodOctetTypeSequence", true);
                IntegrationWithExternal.OctetTypeSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.OctetTypeSequence $result = IntegrationWithExternal.OctetTypeSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodOctetTypeSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodOctetTypeSequence

  public IntegrationWithExternal.CharType MethodCharType (IntegrationWithExternal.CharType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodCharType", true);
                IntegrationWithExternal.CharTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.CharType $result = IntegrationWithExternal.CharTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodCharType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodCharType

  public IntegrationWithExternal.CharTypeArray MethodCharTypeArray (IntegrationWithExternal.CharTypeArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodCharTypeArray", true);
                IntegrationWithExternal.CharTypeArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.CharTypeArray $result = IntegrationWithExternal.CharTypeArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodCharTypeArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodCharTypeArray

  public IntegrationWithExternal.CharTypeSequence MethodCharTypeSequence (IntegrationWithExternal.CharTypeSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodCharTypeSequence", true);
                IntegrationWithExternal.CharTypeSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.CharTypeSequence $result = IntegrationWithExternal.CharTypeSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodCharTypeSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodCharTypeSequence

  public IntegrationWithExternal.WideCharType MethodWideCharType (IntegrationWithExternal.WideCharType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodWideCharType", true);
                IntegrationWithExternal.WideCharTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.WideCharType $result = IntegrationWithExternal.WideCharTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodWideCharType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodWideCharType

  public IntegrationWithExternal.WideCharTypeArray MethodWideCharTypeArray (IntegrationWithExternal.WideCharTypeArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodWideCharTypeArray", true);
                IntegrationWithExternal.WideCharTypeArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.WideCharTypeArray $result = IntegrationWithExternal.WideCharTypeArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodWideCharTypeArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodWideCharTypeArray

  public IntegrationWithExternal.WideCharTypeSequence MethodWideCharTypeSequence (IntegrationWithExternal.WideCharTypeSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodWideCharTypeSequence", true);
                IntegrationWithExternal.WideCharTypeSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.WideCharTypeSequence $result = IntegrationWithExternal.WideCharTypeSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodWideCharTypeSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodWideCharTypeSequence

  public IntegrationWithExternal.StringType MethodStringType (IntegrationWithExternal.StringType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodStringType", true);
                IntegrationWithExternal.StringTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.StringType $result = IntegrationWithExternal.StringTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodStringType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodStringType

  public IntegrationWithExternal.StringTypeArray MethodStringTypeArray (IntegrationWithExternal.StringTypeArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodStringTypeArray", true);
                IntegrationWithExternal.StringTypeArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.StringTypeArray $result = IntegrationWithExternal.StringTypeArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodStringTypeArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodStringTypeArray

  public IntegrationWithExternal.StringTypeSequence MethodStringTypeSequence (IntegrationWithExternal.StringTypeSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodStringTypeSequence", true);
                IntegrationWithExternal.StringTypeSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.StringTypeSequence $result = IntegrationWithExternal.StringTypeSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodStringTypeSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodStringTypeSequence

  public IntegrationWithExternal.WideStringType MethodWideStringType (IntegrationWithExternal.WideStringType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodWideStringType", true);
                IntegrationWithExternal.WideStringTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.WideStringType $result = IntegrationWithExternal.WideStringTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodWideStringType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodWideStringType

  public IntegrationWithExternal.WideStringTypeArray MethodWideStringTypeArray (IntegrationWithExternal.WideStringTypeArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodWideStringTypeArray", true);
                IntegrationWithExternal.WideStringTypeArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.WideStringTypeArray $result = IntegrationWithExternal.WideStringTypeArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodWideStringTypeArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodWideStringTypeArray

  public IntegrationWithExternal.WideStringTypeSequence MethodWideStringTypeSequence (IntegrationWithExternal.WideStringTypeSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodWideStringTypeSequence", true);
                IntegrationWithExternal.WideStringTypeSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.WideStringTypeSequence $result = IntegrationWithExternal.WideStringTypeSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodWideStringTypeSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodWideStringTypeSequence

  public IntegrationWithExternal.ShortType MethodShortType (IntegrationWithExternal.ShortType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodShortType", true);
                IntegrationWithExternal.ShortTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.ShortType $result = IntegrationWithExternal.ShortTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodShortType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodShortType

  public IntegrationWithExternal.ShortTypeArray MethodShortTypeArray (IntegrationWithExternal.ShortTypeArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodShortTypeArray", true);
                IntegrationWithExternal.ShortTypeArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.ShortTypeArray $result = IntegrationWithExternal.ShortTypeArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodShortTypeArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodShortTypeArray

  public IntegrationWithExternal.ShortTypeSequence MethodShortTypeSequence (IntegrationWithExternal.ShortTypeSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodShortTypeSequence", true);
                IntegrationWithExternal.ShortTypeSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.ShortTypeSequence $result = IntegrationWithExternal.ShortTypeSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodShortTypeSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodShortTypeSequence

  public IntegrationWithExternal.UnsignedShortType MethodUnsignedShortType (IntegrationWithExternal.UnsignedShortType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodUnsignedShortType", true);
                IntegrationWithExternal.UnsignedShortTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.UnsignedShortType $result = IntegrationWithExternal.UnsignedShortTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodUnsignedShortType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodUnsignedShortType

  public IntegrationWithExternal.UnsignedShortTypeArray MethodUnsignedShortTypeArray (IntegrationWithExternal.UnsignedShortTypeArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodUnsignedShortTypeArray", true);
                IntegrationWithExternal.UnsignedShortTypeArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.UnsignedShortTypeArray $result = IntegrationWithExternal.UnsignedShortTypeArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodUnsignedShortTypeArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodUnsignedShortTypeArray

  public IntegrationWithExternal.UnsignedShortTypeSequence MethodUnsignedShortTypeSequence (IntegrationWithExternal.UnsignedShortTypeSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodUnsignedShortTypeSequence", true);
                IntegrationWithExternal.UnsignedShortTypeSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.UnsignedShortTypeSequence $result = IntegrationWithExternal.UnsignedShortTypeSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodUnsignedShortTypeSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodUnsignedShortTypeSequence

  public IntegrationWithExternal.LongType MethodLongType (IntegrationWithExternal.LongType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodLongType", true);
                IntegrationWithExternal.LongTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.LongType $result = IntegrationWithExternal.LongTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodLongType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodLongType

  public IntegrationWithExternal.LongTypeArray MethodLongTypeArray (IntegrationWithExternal.LongTypeArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodLongTypeArray", true);
                IntegrationWithExternal.LongTypeArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.LongTypeArray $result = IntegrationWithExternal.LongTypeArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodLongTypeArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodLongTypeArray

  public IntegrationWithExternal.LongTypeSequence MethodLongTypeSequence (IntegrationWithExternal.LongTypeSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodLongTypeSequence", true);
                IntegrationWithExternal.LongTypeSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.LongTypeSequence $result = IntegrationWithExternal.LongTypeSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodLongTypeSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodLongTypeSequence

  public IntegrationWithExternal.UnsignedLongType MethodUnsignedLongType (IntegrationWithExternal.UnsignedLongType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodUnsignedLongType", true);
                IntegrationWithExternal.UnsignedLongTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.UnsignedLongType $result = IntegrationWithExternal.UnsignedLongTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodUnsignedLongType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodUnsignedLongType

  public IntegrationWithExternal.UnsignedLongTypeArray MethodUnsignedLongTypeArray (IntegrationWithExternal.UnsignedLongTypeArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodUnsignedLongTypeArray", true);
                IntegrationWithExternal.UnsignedLongTypeArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.UnsignedLongTypeArray $result = IntegrationWithExternal.UnsignedLongTypeArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodUnsignedLongTypeArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodUnsignedLongTypeArray

  public IntegrationWithExternal.UnsignedLongTypeSequence MethodUnsignedLongTypeSequence (IntegrationWithExternal.UnsignedLongTypeSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodUnsignedLongTypeSequence", true);
                IntegrationWithExternal.UnsignedLongTypeSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.UnsignedLongTypeSequence $result = IntegrationWithExternal.UnsignedLongTypeSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodUnsignedLongTypeSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodUnsignedLongTypeSequence

  public IntegrationWithExternal.FloatType MethodFloatType (IntegrationWithExternal.FloatType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodFloatType", true);
                IntegrationWithExternal.FloatTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.FloatType $result = IntegrationWithExternal.FloatTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodFloatType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodFloatType

  public IntegrationWithExternal.FloatTypeArray MethodFloatTypeArray (IntegrationWithExternal.FloatTypeArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodFloatTypeArray", true);
                IntegrationWithExternal.FloatTypeArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.FloatTypeArray $result = IntegrationWithExternal.FloatTypeArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodFloatTypeArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodFloatTypeArray

  public IntegrationWithExternal.FloatTypeSequence MethodFloatTypeSequence (IntegrationWithExternal.FloatTypeSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodFloatTypeSequence", true);
                IntegrationWithExternal.FloatTypeSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.FloatTypeSequence $result = IntegrationWithExternal.FloatTypeSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodFloatTypeSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodFloatTypeSequence

  public IntegrationWithExternal.DoubleType MethodDoubleType (IntegrationWithExternal.DoubleType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodDoubleType", true);
                IntegrationWithExternal.DoubleTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.DoubleType $result = IntegrationWithExternal.DoubleTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodDoubleType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodDoubleType

  public IntegrationWithExternal.DoubleTypeArray MethodDoubleTypeArray (IntegrationWithExternal.DoubleTypeArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodDoubleTypeArray", true);
                IntegrationWithExternal.DoubleTypeArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.DoubleTypeArray $result = IntegrationWithExternal.DoubleTypeArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodDoubleTypeArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodDoubleTypeArray

  public IntegrationWithExternal.DoubleTypeSequence MethodDoubleTypeSequence (IntegrationWithExternal.DoubleTypeSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodDoubleTypeSequence", true);
                IntegrationWithExternal.DoubleTypeSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.DoubleTypeSequence $result = IntegrationWithExternal.DoubleTypeSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodDoubleTypeSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodDoubleTypeSequence

  public IntegrationWithExternal.EnumValueType MethodEnumValueType (IntegrationWithExternal.EnumValueType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodEnumValueType", true);
                IntegrationWithExternal.EnumValueTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.EnumValueType $result = IntegrationWithExternal.EnumValueTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodEnumValueType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodEnumValueType

  public IntegrationWithExternal.EnumValueArray MethodEnumValueArray (IntegrationWithExternal.EnumValueArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodEnumValueArray", true);
                IntegrationWithExternal.EnumValueArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.EnumValueArray $result = IntegrationWithExternal.EnumValueArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodEnumValueArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodEnumValueArray

  public IntegrationWithExternal.EnumValueTypeSequence MethodEnumValueTypeSequence (IntegrationWithExternal.EnumValueTypeSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodEnumValueTypeSequence", true);
                IntegrationWithExternal.EnumValueTypeSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.EnumValueTypeSequence $result = IntegrationWithExternal.EnumValueTypeSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodEnumValueTypeSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodEnumValueTypeSequence

  public IntegrationWithExternal.LongLongType MethodLongLongType (IntegrationWithExternal.LongLongType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodLongLongType", true);
                IntegrationWithExternal.LongLongTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.LongLongType $result = IntegrationWithExternal.LongLongTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodLongLongType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodLongLongType

  public IntegrationWithExternal.LongLongTypeArray MethodLongLongTypeArray (IntegrationWithExternal.LongLongTypeArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodLongLongTypeArray", true);
                IntegrationWithExternal.LongLongTypeArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.LongLongTypeArray $result = IntegrationWithExternal.LongLongTypeArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodLongLongTypeArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodLongLongTypeArray

  public IntegrationWithExternal.LongLongTypeSeqSequence MethodLongLongTypeSeqSequence (IntegrationWithExternal.LongLongTypeSeqSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodLongLongTypeSeqSequence", true);
                IntegrationWithExternal.LongLongTypeSeqSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.LongLongTypeSeqSequence $result = IntegrationWithExternal.LongLongTypeSeqSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodLongLongTypeSeqSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodLongLongTypeSeqSequence

  public IntegrationWithExternal.UnsignedLongLongType MethodUnsignedLongLongType (IntegrationWithExternal.UnsignedLongLongType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodUnsignedLongLongType", true);
                IntegrationWithExternal.UnsignedLongLongTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.UnsignedLongLongType $result = IntegrationWithExternal.UnsignedLongLongTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodUnsignedLongLongType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodUnsignedLongLongType

  public IntegrationWithExternal.UnsignedLongLongTypeArray MethodUnsignedLongLongTypeArray (IntegrationWithExternal.UnsignedLongLongTypeArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodUnsignedLongLongTypeArray", true);
                IntegrationWithExternal.UnsignedLongLongTypeArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.UnsignedLongLongTypeArray $result = IntegrationWithExternal.UnsignedLongLongTypeArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodUnsignedLongLongTypeArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodUnsignedLongLongTypeArray

  public IntegrationWithExternal.UnsignedLongLongTypeSequence MethodUnsignedLongLongTypeSequence (IntegrationWithExternal.UnsignedLongLongTypeSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodUnsignedLongLongTypeSequence", true);
                IntegrationWithExternal.UnsignedLongLongTypeSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.UnsignedLongLongTypeSequence $result = IntegrationWithExternal.UnsignedLongLongTypeSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodUnsignedLongLongTypeSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodUnsignedLongLongTypeSequence

  public IntegrationWithExternal.BooleanType MethodBooleanType (IntegrationWithExternal.BooleanType data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodBooleanType", true);
                IntegrationWithExternal.BooleanTypeHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.BooleanType $result = IntegrationWithExternal.BooleanTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodBooleanType (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodBooleanType

  public IntegrationWithExternal.BooleanTypeArray MethodBooleanTypeArray (IntegrationWithExternal.BooleanTypeArray data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodBooleanTypeArray", true);
                IntegrationWithExternal.BooleanTypeArrayHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.BooleanTypeArray $result = IntegrationWithExternal.BooleanTypeArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodBooleanTypeArray (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodBooleanTypeArray

  public IntegrationWithExternal.BooleanTypeSequence MethodBooleanTypeSequence (IntegrationWithExternal.BooleanTypeSequence data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("MethodBooleanTypeSequence", true);
                IntegrationWithExternal.BooleanTypeSequenceHelper.write ($out, data);
                $in = _invoke ($out);
                IntegrationWithExternal.BooleanTypeSequence $result = IntegrationWithExternal.BooleanTypeSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return MethodBooleanTypeSequence (data        );
            } finally {
                _releaseReply ($in);
            }
  } // MethodBooleanTypeSequence

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:IntegrationWithExternal/IIntegrationWithExternal:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _IIntegrationWithExternalStub
