package IntegrationWithExternal;


/**
* IntegrationWithExternal/DoubleType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class DoubleType implements org.omg.CORBA.portable.IDLEntity
{
  public double Value = (double)0;

  public DoubleType ()
  {
  } // ctor

  public DoubleType (double _Value)
  {
    Value = _Value;
  } // ctor

} // class DoubleType
