package IntegrationWithExternal;

/**
* IntegrationWithExternal/DoubleTypeArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class DoubleTypeArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternal.DoubleTypeArray value = null;

  public DoubleTypeArrayHolder ()
  {
  }

  public DoubleTypeArrayHolder (IntegrationWithExternal.DoubleTypeArray initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternal.DoubleTypeArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternal.DoubleTypeArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternal.DoubleTypeArrayHelper.type ();
  }

}
