package IntegrationWithExternal;


/**
* IntegrationWithExternal/DoubleTypeArray.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class DoubleTypeArray implements org.omg.CORBA.portable.IDLEntity
{
  public double Value[] = null;

  public DoubleTypeArray ()
  {
  } // ctor

  public DoubleTypeArray (double[] _Value)
  {
    Value = _Value;
  } // ctor

} // class DoubleTypeArray
