package IntegrationWithExternal;

/**
* IntegrationWithExternal/EnumValueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class EnumValueHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternal.EnumValue value = null;

  public EnumValueHolder ()
  {
  }

  public EnumValueHolder (IntegrationWithExternal.EnumValue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternal.EnumValueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternal.EnumValueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternal.EnumValueHelper.type ();
  }

}
