package IntegrationWithExternal;


/**
* IntegrationWithExternal/EnumValueTypeSequence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class EnumValueTypeSequence implements org.omg.CORBA.portable.IDLEntity
{
  public IntegrationWithExternal.EnumValueType Seq[] = null;

  public EnumValueTypeSequence ()
  {
  } // ctor

  public EnumValueTypeSequence (IntegrationWithExternal.EnumValueType[] _Seq)
  {
    Seq = _Seq;
  } // ctor

} // class EnumValueTypeSequence
