package IntegrationWithExternal;


/**
* IntegrationWithExternal/EnumValueTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

abstract public class EnumValueTypeHelper
{
  private static String  _id = "IDL:IntegrationWithExternal/EnumValueType:1.0";

  public static void insert (org.omg.CORBA.Any a, IntegrationWithExternal.EnumValueType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static IntegrationWithExternal.EnumValueType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = IntegrationWithExternal.EnumValueHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "Value",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (IntegrationWithExternal.EnumValueTypeHelper.id (), "EnumValueType", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static IntegrationWithExternal.EnumValueType read (org.omg.CORBA.portable.InputStream istream)
  {
    IntegrationWithExternal.EnumValueType value = new IntegrationWithExternal.EnumValueType ();
    value.Value = IntegrationWithExternal.EnumValueHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, IntegrationWithExternal.EnumValueType value)
  {
    IntegrationWithExternal.EnumValueHelper.write (ostream, value.Value);
  }

}
