package IntegrationWithExternal;


/**
* IntegrationWithExternal/EnumValueType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class EnumValueType implements org.omg.CORBA.portable.IDLEntity
{
  public IntegrationWithExternal.EnumValue Value = null;

  public EnumValueType ()
  {
  } // ctor

  public EnumValueType (IntegrationWithExternal.EnumValue _Value)
  {
    Value = _Value;
  } // ctor

} // class EnumValueType
