package IntegrationWithExternal;


/**
* IntegrationWithExternal/FloatTypeArray.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class FloatTypeArray implements org.omg.CORBA.portable.IDLEntity
{
  public float Value[] = null;

  public FloatTypeArray ()
  {
  } // ctor

  public FloatTypeArray (float[] _Value)
  {
    Value = _Value;
  } // ctor

} // class FloatTypeArray
