package IntegrationWithExternal;


/**
* IntegrationWithExternal/LongTypeArray.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:22 PM SAST
*/

public final class LongTypeArray implements org.omg.CORBA.portable.IDLEntity
{
  public int Value[] = null;

  public LongTypeArray ()
  {
  } // ctor

  public LongTypeArray (int[] _Value)
  {
    Value = _Value;
  } // ctor

} // class LongTypeArray
