package IntegrationWithExternal;

/**
* IntegrationWithExternal/LongTypeArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:22 PM SAST
*/

public final class LongTypeArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternal.LongTypeArray value = null;

  public LongTypeArrayHolder ()
  {
  }

  public LongTypeArrayHolder (IntegrationWithExternal.LongTypeArray initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternal.LongTypeArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternal.LongTypeArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternal.LongTypeArrayHelper.type ();
  }

}
