package IntegrationWithExternal;


/**
* IntegrationWithExternal/OctetTypeSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:22 PM SAST
*/

public final class OctetTypeSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternal.OctetType value[] = null;

  public OctetTypeSeqHolder ()
  {
  }

  public OctetTypeSeqHolder (IntegrationWithExternal.OctetType[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternal.OctetTypeSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternal.OctetTypeSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternal.OctetTypeSeqHelper.type ();
  }

}
