package IntegrationWithExternal;


/**
* IntegrationWithExternal/ShortType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:22 PM SAST
*/

public final class ShortType implements org.omg.CORBA.portable.IDLEntity
{
  public short Value = (short)0;

  public ShortType ()
  {
  } // ctor

  public ShortType (short _Value)
  {
    Value = _Value;
  } // ctor

} // class ShortType
