package IntegrationWithExternal;

/**
* IntegrationWithExternal/StringTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:22 PM SAST
*/

public final class StringTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternal.StringType value = null;

  public StringTypeHolder ()
  {
  }

  public StringTypeHolder (IntegrationWithExternal.StringType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternal.StringTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternal.StringTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternal.StringTypeHelper.type ();
  }

}
