package IntegrationWithExternal;


/**
* IntegrationWithExternal/UnsignedLongTypeSequence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class UnsignedLongTypeSequence implements org.omg.CORBA.portable.IDLEntity
{
  public IntegrationWithExternal.UnsignedLongType Seq[] = null;

  public UnsignedLongTypeSequence ()
  {
  } // ctor

  public UnsignedLongTypeSequence (IntegrationWithExternal.UnsignedLongType[] _Seq)
  {
    Seq = _Seq;
  } // ctor

} // class UnsignedLongTypeSequence
