package IntegrationWithExternal;

/**
* IntegrationWithExternal/UnsignedShortTypeSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:22 PM SAST
*/

public final class UnsignedShortTypeSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternal.UnsignedShortTypeSequence value = null;

  public UnsignedShortTypeSequenceHolder ()
  {
  }

  public UnsignedShortTypeSequenceHolder (IntegrationWithExternal.UnsignedShortTypeSequence initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternal.UnsignedShortTypeSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternal.UnsignedShortTypeSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternal.UnsignedShortTypeSequenceHelper.type ();
  }

}
