package IntegrationWithExternal;

/**
* IntegrationWithExternal/WideCharTypeSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:22 PM SAST
*/

public final class WideCharTypeSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternal.WideCharTypeSequence value = null;

  public WideCharTypeSequenceHolder ()
  {
  }

  public WideCharTypeSequenceHolder (IntegrationWithExternal.WideCharTypeSequence initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternal.WideCharTypeSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternal.WideCharTypeSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternal.WideCharTypeSequenceHelper.type ();
  }

}
