package IntegrationWithExternal;

/**
* IntegrationWithExternal/WideStringTypeSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:22 PM SAST
*/

public final class WideStringTypeSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternal.WideStringTypeSequence value = null;

  public WideStringTypeSequenceHolder ()
  {
  }

  public WideStringTypeSequenceHolder (IntegrationWithExternal.WideStringTypeSequence initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternal.WideStringTypeSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternal.WideStringTypeSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternal.WideStringTypeSequenceHelper.type ();
  }

}
