package IntegrationWithExternal;


/**
* IntegrationWithExternal/WideStringTypeSequenceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:22 PM SAST
*/

abstract public class WideStringTypeSequenceHelper
{
  private static String  _id = "IDL:IntegrationWithExternal/WideStringTypeSequence:1.0";

  public static void insert (org.omg.CORBA.Any a, IntegrationWithExternal.WideStringTypeSequence that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static IntegrationWithExternal.WideStringTypeSequence extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = IntegrationWithExternal.WideStringTypeHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (IntegrationWithExternal.WideStringTypeSeqHelper.id (), "WideStringTypeSeq", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "Seq",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (IntegrationWithExternal.WideStringTypeSequenceHelper.id (), "WideStringTypeSequence", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static IntegrationWithExternal.WideStringTypeSequence read (org.omg.CORBA.portable.InputStream istream)
  {
    IntegrationWithExternal.WideStringTypeSequence value = new IntegrationWithExternal.WideStringTypeSequence ();
    value.Seq = IntegrationWithExternal.WideStringTypeSeqHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, IntegrationWithExternal.WideStringTypeSequence value)
  {
    IntegrationWithExternal.WideStringTypeSeqHelper.write (ostream, value.Seq);
  }

}
