package IntegrationWithExternal;


/**
* IntegrationWithExternal/WideStringTypeArray.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:22 PM SAST
*/

public final class WideStringTypeArray implements org.omg.CORBA.portable.IDLEntity
{
  public String Value[] = null;

  public WideStringTypeArray ()
  {
  } // ctor

  public WideStringTypeArray (String[] _Value)
  {
    Value = _Value;
  } // ctor

} // class WideStringTypeArray
