package IntegrationWithExternal;


/**
* IntegrationWithExternal/WideStringTypeSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test.idl
* Saturday, June 13, 2020 11:01:22 PM SAST
*/

public final class WideStringTypeSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternal.WideStringType value[] = null;

  public WideStringTypeSeqHolder ()
  {
  }

  public WideStringTypeSeqHolder (IntegrationWithExternal.WideStringType[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternal.WideStringTypeSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternal.WideStringTypeSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternal.WideStringTypeSeqHelper.type ();
  }

}
