package IntegrationWithExternalNotAligned;


/**
* IntegrationWithExternalNotAligned/CharType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class CharType implements org.omg.CORBA.portable.IDLEntity
{
  public byte dummy = (byte)0;
  public char Value = (char)0;

  public CharType ()
  {
  } // ctor

  public CharType (byte _dummy, char _Value)
  {
    dummy = _dummy;
    Value = _Value;
  } // ctor

} // class CharType
