package IntegrationWithExternalNotAligned;


/**
* IntegrationWithExternalNotAligned/DoubleType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class DoubleType implements org.omg.CORBA.portable.IDLEntity
{
  public byte dummy = (byte)0;
  public double Value = (double)0;

  public DoubleType ()
  {
  } // ctor

  public DoubleType (byte _dummy, double _Value)
  {
    dummy = _dummy;
    Value = _Value;
  } // ctor

} // class DoubleType
