package IntegrationWithExternalNotAligned;


/**
* IntegrationWithExternalNotAligned/EnumValueTypeSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class EnumValueTypeSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternalNotAligned.EnumValueType value[] = null;

  public EnumValueTypeSeqHolder ()
  {
  }

  public EnumValueTypeSeqHolder (IntegrationWithExternalNotAligned.EnumValueType[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternalNotAligned.EnumValueTypeSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternalNotAligned.EnumValueTypeSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternalNotAligned.EnumValueTypeSeqHelper.type ();
  }

}
