package IntegrationWithExternalNotAligned;

/**
* IntegrationWithExternalNotAligned/FloatTypeSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class FloatTypeSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternalNotAligned.FloatTypeSequence value = null;

  public FloatTypeSequenceHolder ()
  {
  }

  public FloatTypeSequenceHolder (IntegrationWithExternalNotAligned.FloatTypeSequence initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternalNotAligned.FloatTypeSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternalNotAligned.FloatTypeSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternalNotAligned.FloatTypeSequenceHelper.type ();
  }

}
