package IntegrationWithExternalNotAligned;


/**
* IntegrationWithExternalNotAligned/IIntegrationWithExternalNotAligned.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public interface IIntegrationWithExternalNotAligned extends IIntegrationWithExternalNotAlignedOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IIntegrationWithExternalNotAligned
