package IntegrationWithExternalNotAligned;

/**
* IntegrationWithExternalNotAligned/LongLongTypeSeqSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class LongLongTypeSeqSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternalNotAligned.LongLongTypeSeqSequence value = null;

  public LongLongTypeSeqSequenceHolder ()
  {
  }

  public LongLongTypeSeqSequenceHolder (IntegrationWithExternalNotAligned.LongLongTypeSeqSequence initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternalNotAligned.LongLongTypeSeqSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternalNotAligned.LongLongTypeSeqSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternalNotAligned.LongLongTypeSeqSequenceHelper.type ();
  }

}
