package IntegrationWithExternalNotAligned;


/**
* IntegrationWithExternalNotAligned/LongType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class LongType implements org.omg.CORBA.portable.IDLEntity
{
  public byte dummy = (byte)0;
  public int Value = (int)0;

  public LongType ()
  {
  } // ctor

  public LongType (byte _dummy, int _Value)
  {
    dummy = _dummy;
    Value = _Value;
  } // ctor

} // class LongType
