package IntegrationWithExternalNotAligned;

/**
* IntegrationWithExternalNotAligned/LongTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class LongTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternalNotAligned.LongType value = null;

  public LongTypeHolder ()
  {
  }

  public LongTypeHolder (IntegrationWithExternalNotAligned.LongType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternalNotAligned.LongTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternalNotAligned.LongTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternalNotAligned.LongTypeHelper.type ();
  }

}
