package IntegrationWithExternalNotAligned;


/**
* IntegrationWithExternalNotAligned/OctetTypeSequence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class OctetTypeSequence implements org.omg.CORBA.portable.IDLEntity
{
  public byte dummy = (byte)0;
  public IntegrationWithExternalNotAligned.OctetType Seq[] = null;

  public OctetTypeSequence ()
  {
  } // ctor

  public OctetTypeSequence (byte _dummy, IntegrationWithExternalNotAligned.OctetType[] _Seq)
  {
    dummy = _dummy;
    Seq = _Seq;
  } // ctor

} // class OctetTypeSequence
