package IntegrationWithExternalNotAligned;

/**
* IntegrationWithExternalNotAligned/OctetTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class OctetTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternalNotAligned.OctetType value = null;

  public OctetTypeHolder ()
  {
  }

  public OctetTypeHolder (IntegrationWithExternalNotAligned.OctetType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternalNotAligned.OctetTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternalNotAligned.OctetTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternalNotAligned.OctetTypeHelper.type ();
  }

}
