package IntegrationWithExternalNotAligned;


/**
* IntegrationWithExternalNotAligned/ShortTypeSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class ShortTypeSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternalNotAligned.ShortType value[] = null;

  public ShortTypeSeqHolder ()
  {
  }

  public ShortTypeSeqHolder (IntegrationWithExternalNotAligned.ShortType[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternalNotAligned.ShortTypeSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternalNotAligned.ShortTypeSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternalNotAligned.ShortTypeSeqHelper.type ();
  }

}
