package IntegrationWithExternalNotAligned;


/**
* IntegrationWithExternalNotAligned/StringTypeSequence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class StringTypeSequence implements org.omg.CORBA.portable.IDLEntity
{
  public byte dummy = (byte)0;
  public IntegrationWithExternalNotAligned.StringType Seq[] = null;

  public StringTypeSequence ()
  {
  } // ctor

  public StringTypeSequence (byte _dummy, IntegrationWithExternalNotAligned.StringType[] _Seq)
  {
    dummy = _dummy;
    Seq = _Seq;
  } // ctor

} // class StringTypeSequence
