package IntegrationWithExternalNotAligned;


/**
* IntegrationWithExternalNotAligned/UnsignedShortTypeArray.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class UnsignedShortTypeArray implements org.omg.CORBA.portable.IDLEntity
{
  public byte dummy = (byte)0;
  public short Value[] = null;

  public UnsignedShortTypeArray ()
  {
  } // ctor

  public UnsignedShortTypeArray (byte _dummy, short[] _Value)
  {
    dummy = _dummy;
    Value = _Value;
  } // ctor

} // class UnsignedShortTypeArray
