package IntegrationWithExternalNotAligned;

/**
* IntegrationWithExternalNotAligned/UnsignedLongLongTypeArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class UnsignedLongLongTypeArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternalNotAligned.UnsignedLongLongTypeArray value = null;

  public UnsignedLongLongTypeArrayHolder ()
  {
  }

  public UnsignedLongLongTypeArrayHolder (IntegrationWithExternalNotAligned.UnsignedLongLongTypeArray initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternalNotAligned.UnsignedLongLongTypeArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternalNotAligned.UnsignedLongLongTypeArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternalNotAligned.UnsignedLongLongTypeArrayHelper.type ();
  }

}
