package IntegrationWithExternalNotAligned;

/**
* IntegrationWithExternalNotAligned/UnsignedShortTypeArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class UnsignedShortTypeArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternalNotAligned.UnsignedShortTypeArray value = null;

  public UnsignedShortTypeArrayHolder ()
  {
  }

  public UnsignedShortTypeArrayHolder (IntegrationWithExternalNotAligned.UnsignedShortTypeArray initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternalNotAligned.UnsignedShortTypeArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternalNotAligned.UnsignedShortTypeArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternalNotAligned.UnsignedShortTypeArrayHelper.type ();
  }

}
