package IntegrationWithExternalNotAligned;


/**
* IntegrationWithExternalNotAligned/UnsignedLongLongType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class UnsignedLongLongType implements org.omg.CORBA.portable.IDLEntity
{
  public byte dummy = (byte)0;
  public long Value = (long)0;

  public UnsignedLongLongType ()
  {
  } // ctor

  public UnsignedLongLongType (byte _dummy, long _Value)
  {
    dummy = _dummy;
    Value = _Value;
  } // ctor

} // class UnsignedLongLongType
