package IntegrationWithExternalNotAligned;

/**
* IntegrationWithExternalNotAligned/UnsignedShortTypeSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class UnsignedShortTypeSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public IntegrationWithExternalNotAligned.UnsignedShortTypeSequence value = null;

  public UnsignedShortTypeSequenceHolder ()
  {
  }

  public UnsignedShortTypeSequenceHolder (IntegrationWithExternalNotAligned.UnsignedShortTypeSequence initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntegrationWithExternalNotAligned.UnsignedShortTypeSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntegrationWithExternalNotAligned.UnsignedShortTypeSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntegrationWithExternalNotAligned.UnsignedShortTypeSequenceHelper.type ();
  }

}
