package IntegrationWithExternalNotAligned;


/**
* IntegrationWithExternalNotAligned/WideStringTypeSequence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class WideStringTypeSequence implements org.omg.CORBA.portable.IDLEntity
{
  public byte dummy = (byte)0;
  public IntegrationWithExternalNotAligned.WideStringType Seq[] = null;

  public WideStringTypeSequence ()
  {
  } // ctor

  public WideStringTypeSequence (byte _dummy, IntegrationWithExternalNotAligned.WideStringType[] _Seq)
  {
    dummy = _dummy;
    Seq = _Seq;
  } // ctor

} // class WideStringTypeSequence
