package IntegrationWithExternalNotAligned;


/**
* IntegrationWithExternalNotAligned/WideCharTypeSequence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

public final class WideCharTypeSequence implements org.omg.CORBA.portable.IDLEntity
{
  public byte dummy = (byte)0;
  public IntegrationWithExternalNotAligned.WideCharType Seq[] = null;

  public WideCharTypeSequence ()
  {
  } // ctor

  public WideCharTypeSequence (byte _dummy, IntegrationWithExternalNotAligned.WideCharType[] _Seq)
  {
    dummy = _dummy;
    Seq = _Seq;
  } // ctor

} // class WideCharTypeSequence
