package IntegrationWithExternalNotAligned;


/**
* IntegrationWithExternalNotAligned/WideCharTypeSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./test2.idl
* Saturday, June 13, 2020 11:01:23 PM SAST
*/

abstract public class WideCharTypeSeqHelper
{
  private static String  _id = "IDL:IntegrationWithExternalNotAligned/WideCharTypeSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, IntegrationWithExternalNotAligned.WideCharType[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static IntegrationWithExternalNotAligned.WideCharType[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = IntegrationWithExternalNotAligned.WideCharTypeHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (IntegrationWithExternalNotAligned.WideCharTypeSeqHelper.id (), "WideCharTypeSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static IntegrationWithExternalNotAligned.WideCharType[] read (org.omg.CORBA.portable.InputStream istream)
  {
    IntegrationWithExternalNotAligned.WideCharType value[] = null;
    int _len0 = istream.read_long ();
    value = new IntegrationWithExternalNotAligned.WideCharType[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = IntegrationWithExternalNotAligned.WideCharTypeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, IntegrationWithExternalNotAligned.WideCharType[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      IntegrationWithExternalNotAligned.WideCharTypeHelper.write (ostream, value[_i0]);
  }

}
