package HelloApp;

/**
* HelloApp/PersonHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* Saturday, May 30, 2020 6:17:55 AM SAST
*/

public final class PersonHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.Person value = null;

  public PersonHolder ()
  {
  }

  public PersonHolder (HelloApp.Person initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.PersonHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.PersonHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.PersonHelper.type ();
  }

}
