// Code generated by me. DO NOT EDIT.

package IOP

import __goidl__ "github.com/bhbosman/goidl"

// TypeDef declaration: "IOP::EncodingFormat", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "IOP::EncodingFormat" from: "int16"
type IopEncodingFormat int16

//noinspection GoSnakeCaseUsage
type IopEncodingFormat_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IopEncodingFormatId_Const = "IDL:omg.org/IOP/EncodingFormat:1.0"

func (self IopEncodingFormat_Helper) Id() string {
	return IopEncodingFormatId_Const
}

func (self IopEncodingFormat_Helper) Read(stream __goidl__.IReadAny) (int16, error) {
	result, err := __goidl__.IdlInt16Helper.Read(stream)
	return result, err
}

func (self IopEncodingFormat_Helper) Write(stream __goidl__.IWriteAny, v int16) error {
	return __goidl__.IdlInt16Helper.Write(stream, v)
}


//noinspection GoUnusedGlobalVariable
var IopEncodingFormatHelper = IopEncodingFormat_Helper{}

func init() {
}
