// Code generated by me. DO NOT EDIT.

package IOP

import __goidl__ "github.com/bhbosman/goidl"

// TypeDef declaration: "IOP::ProfileId", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "IOP::ProfileId" from: "uint32"
type IopProfileId uint32

//noinspection GoSnakeCaseUsage
type IopProfileId_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IopProfileIdId_Const = "IDL:omg.org/IOP/ProfileId:1.0"

func (self IopProfileId_Helper) Id() string {
	return IopProfileIdId_Const
}

func (self IopProfileId_Helper) Read(stream __goidl__.IReadAny) (uint32, error) {
	result, err := __goidl__.IdlUInt32Helper.Read(stream)
	return result, err
}

func (self IopProfileId_Helper) Write(stream __goidl__.IWriteAny, v uint32) error {
	return __goidl__.IdlUInt32Helper.Write(stream, v)
}


//noinspection GoUnusedGlobalVariable
var IopProfileIdHelper = IopProfileId_Helper{}

func init() {
}
