// Code generated by me. DO NOT EDIT.

package IOP

import __fmt__ "fmt"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Exception declaration: "IOP::Codec::FormatMismatch", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type IopCodecFormatMismatch struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const IopCodecFormatMismatchId_Const = "IDL:omg.org/IOP/Codec/FormatMismatch:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopCodecFormatMismatch() *IopCodecFormatMismatch {
	//noinspection GoRedundantConversion
	return &IopCodecFormatMismatch{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecFormatMismatchId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopCodecFormatMismatch() *IopCodecFormatMismatch {
	//noinspection GoRedundantConversion
	return &IopCodecFormatMismatch{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecFormatMismatchId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopCodecFormatMismatch() *IopCodecFormatMismatch {
	//noinspection GoRedundantConversion
	return &IopCodecFormatMismatch{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecFormatMismatchId_Const,
		},
	}
}

func (self *IopCodecFormatMismatch) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecFormatMismatch) Error() string{
	return 	__fmt__.Sprintf("Error of type IopCodecFormatMismatch(%v)", self.String())
}
func (self *IopCodecFormatMismatch) GoString() string {
	return self.String()
}

func (self *IopCodecFormatMismatch) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecFormatMismatch) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecFormatMismatch) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecFormatMismatch_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopCodecFormatMismatchHelper = IopCodecFormatMismatch_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecFormatMismatchId_Const,
			__yaccidl__.IdlStruct,
			"iop.idl.FormatMismatch.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopCodecFormatMismatch()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewDefaultIopCodecFormatMismatch()
			},
			__reflect__.TypeOf((*IopCodecFormatMismatch)(nil))))
}
