// Code generated by me. DO NOT EDIT.

package IOP

import __goidl__ "github.com/bhbosman/goidl"

// TypeDef declaration: "IOP::ServiceContextList", generatedBy by: "WriteTypeDefOfSequenceDcl"
//Typedef Sequence declaration: IOP::ServiceContextList
type IopServiceContextList []*IopServiceContext

//noinspection GoSnakeCaseUsage
type IopServiceContextList_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IopServiceContextListId_Const = "IDL:omg.org/IOP/ServiceContextList:1.0"

func (self IopServiceContextList_Helper) Id() string {
	return IopServiceContextListId_Const
}

// WriteTypeDefOfSequenceDcl::WriteExtract
func (self IopServiceContextList_Helper) Read(stream __goidl__.IReadAny) (IopServiceContextList, error) {
	n, err := __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		result := make(IopServiceContextList, n)
		var i uint32
		for i = 0; i < n; i++ {
			result[i] = NewDefaultIopServiceContext()
			err = result[i].Read(stream)
			if err != nil {
				return nil, err
			}
		}
		return result, nil
	}
	return nil, nil
}

func (self IopServiceContextList_Helper) Write(stream __goidl__.IWriteAny, v IopServiceContextList) error {
	if v == nil {
		return __goidl__.IdlUInt32Helper.Write(stream, 0)
	}
	err := __goidl__.IdlUInt32Helper.Write(stream, uint32(len(v)))
	if err != nil {
		return nil
	}
	for _, item := range v {
			err = item.Write(stream)
		if err != nil {
			return err
		}
	}
	return err
}


//noinspection GoUnusedGlobalVariable
var IopServiceContextListHelper = IopServiceContextList_Helper{}

func init() {
}
