// Code generated by me. DO NOT EDIT.

package IOP

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Struct declaration: "IOP::Encoding", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopEncoding struct {
	__goidl__.IdlObject
	Format int16 `json:"Format"`
	MajorVersion byte `json:"MajorVersion"`
	MinorVersion byte `json:"MinorVersion"`
}

//noinspection GoSnakeCaseUsage
const IopEncodingId_Const = "IDL:omg.org/IOP/Encoding:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopEncoding() *IopEncoding {
	//noinspection GoRedundantConversion
	return &IopEncoding{
		IdlObject: __goidl__.IdlObject{
			Id: IopEncodingId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "format", Type: "IOP::EncodingFormat" Scope: "IdlTypedef"
		Format: 0,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "major_version", Type: "IdlOctet" Scope: "IdlOctetKind"
		MajorVersion: 0,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "minor_version", Type: "IdlOctet" Scope: "IdlOctetKind"
		MinorVersion: 0,
	}
}

//noinspection GoUnusedExportedFunction
func NewIopEncoding(
	//"StructDclAllParamsConstructorParamService"
	Format int16,
	//"StructDclAllParamsConstructorParamService"
	MajorVersion byte,
	//"StructDclAllParamsConstructorParamService"
	MinorVersion byte) *IopEncoding {
	//noinspection GoRedundantConversion
	return &IopEncoding{
		IdlObject: __goidl__.IdlObject{
			Id: IopEncodingId_Const,
		},
		Format: Format,
		MajorVersion: MajorVersion,
		MinorVersion: MinorVersion,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopEncoding(randomGenerator __goidl__.IRandomDataGenerator) *IopEncoding {
	//noinspection GoRedundantConversion
	return &IopEncoding{
		IdlObject: __goidl__.IdlObject{
			Id: IopEncodingId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "format", Type: "IOP::EncodingFormat" Scope: "IdlTypedef"
		Format: randomGenerator.ShortTypeValue(__reflect__.TypeOf((*IopEncoding)(nil)), "Format"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "major_version", Type: "IdlOctet" Scope: "IdlOctetKind"
		MajorVersion: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IopEncoding)(nil)), "MajorVersion"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "minor_version", Type: "IdlOctet" Scope: "IdlOctetKind"
		MinorVersion: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IopEncoding)(nil)), "MinorVersion"),
	}
}

func (self *IopEncoding) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopEncoding) GoString() string {
	return self.String()
}

func (self *IopEncoding) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(ShortType)
	self.Format, err = __goidl__.IdlInt16Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlOctetKind)
	self.MajorVersion, err = __goidl__.IdlOctetHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlOctetKind)
	self.MinorVersion, err = __goidl__.IdlOctetHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopEncoding) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopEncoding) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(ShortType)
	err = __goidl__.IdlInt16Helper.Write(stream, self.Format)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlOctetKind)
	err = __goidl__.IdlOctetHelper.Write(stream, self.MajorVersion)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlOctetKind)
	err = __goidl__.IdlOctetHelper.Write(stream, self.MinorVersion)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopEncoding_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopEncodingHelper = IopEncoding_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopEncodingId_Const,
			__yaccidl__.IdlStruct,
			"iop.idl.Encoding.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopEncoding()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomIopEncoding(generator)
			},
			__reflect__.TypeOf((*IopEncoding)(nil))))
}
